#ifndef ORDER_CM_H_VAJK20040620
#define ORDER_CM_H_VAJK20040620

// (C) Copyright Vesa Karvonen 2004.
//
//    Distributed under the Boost Software License, Version 1.0.

#include "chaos/preprocessor/seq/reverse.h"

#define ORDER_PP_CM(...) ORDER_PP_CM_B_0(ORDER_PP_CM_UP_0(__VA_ARGS__))
#define ORDER_PP_CM_1(...) ORDER_PP_CM_B_1(ORDER_PP_CM_UP_0(__VA_ARGS__))
#define ORDER_PP_CM_2(...) ORDER_PP_CM_B_2(ORDER_PP_CM_UP_0(__VA_ARGS__))
#define ORDER_PP_CM_3(...) ORDER_PP_CM_B_3(ORDER_PP_CM_UP_0(__VA_ARGS__))
#define ORDER_PP_CM_4(...) ORDER_PP_CM_B_4(ORDER_PP_CM_UP_0(__VA_ARGS__))
#define ORDER_PP_CM_5(...) ORDER_PP_CM_B_5(ORDER_PP_CM_UP_0(__VA_ARGS__))
#define ORDER_PP_CM_6(...) ORDER_PP_CM_B_6(ORDER_PP_CM_UP_0(__VA_ARGS__))
#define ORDER_PP_CM_7(...) ORDER_PP_CM_B_7(ORDER_PP_CM_UP_0(__VA_ARGS__))

#define ORDER_PP_CM_B_0(x) ORDER_PP_CM_ERROR_0(,x))
#define ORDER_PP_CM_B_1(x) ORDER_PP_CM_ERROR_1(,x))
#define ORDER_PP_CM_B_2(x) ORDER_PP_CM_ERROR_2(,x))
#define ORDER_PP_CM_B_3(x) ORDER_PP_CM_ERROR_3(,x))
#define ORDER_PP_CM_B_4(x) ORDER_PP_CM_ERROR_4(,x))
#define ORDER_PP_CM_B_5(x) ORDER_PP_CM_ERROR_5(,x))
#define ORDER_PP_CM_B_6(x) ORDER_PP_CM_ERROR_6(,x))
#define ORDER_PP_CM_B_7(x) ORDER_PP_CM_ERROR_7(,x))

#define ORDER_PP_CM_ERROR_0(P,_,x) ORDER_PP_CM_SCAN_1(,P##x,ORDER_PP_CM_OUTPUT(,
#define ORDER_PP_CM_ERROR_1(P,_,x) ORDER_PP_CM_SCAN_2(,P##x,ORDER_PP_CM_OUTPUT(,
#define ORDER_PP_CM_ERROR_2(P,_,x) ORDER_PP_CM_SCAN_3(,P##x,ORDER_PP_CM_OUTPUT(,
#define ORDER_PP_CM_ERROR_3(P,_,x) ORDER_PP_CM_SCAN_4(,P##x,ORDER_PP_CM_OUTPUT(,
#define ORDER_PP_CM_ERROR_4(P,_,x) ORDER_PP_CM_SCAN_5(,P##x,ORDER_PP_CM_OUTPUT(,
#define ORDER_PP_CM_ERROR_5(P,_,x) ORDER_PP_CM_SCAN_6(,P##x,ORDER_PP_CM_OUTPUT(,
#define ORDER_PP_CM_ERROR_6(P,_,x) ORDER_PP_CM_SCAN_7(,P##x,ORDER_PP_CM_OUTPUT(,
#define ORDER_PP_CM_ERROR_7(P,_,x) ORDER_PP_CM_SCAN_8(,P##x,ORDER_PP_CM_OUTPUT(,

#define ORDER_PP_CM_OUTPUT(P,s) ORDER_PP_CM_OUTPUT_OPEN_A P##s(0,0,)ORDER_PP_CM_OUTPUT_CLOSE_A P##s(0,)

#define ORDER_PP_CM_OUTPUT_OPEN_A(P,m,...) ORDER_PP_CM_EMIT ORDER_PP_EAT()(,m,(,P##__VA_ARGS__),ORDER_PP_CM_OUTPUT_OPEN_B##P
#define ORDER_PP_CM_OUTPUT_OPEN_B(P,m,...) ORDER_PP_CM_EMIT ORDER_PP_EAT()(,m,(,P##__VA_ARGS__),ORDER_PP_CM_OUTPUT_OPEN_A##P
#define ORDER_PP_CM_OUTPUT_OPEN_A0
#define ORDER_PP_CM_OUTPUT_OPEN_B0

#define ORDER_PP_CM_OUTPUT_CLOSE_A(P,...) )ORDER_PP_CM_OUTPUT_CLOSE_B##P
#define ORDER_PP_CM_OUTPUT_CLOSE_B(P,...) )ORDER_PP_CM_OUTPUT_CLOSE_A##P
#define ORDER_PP_CM_OUTPUT_CLOSE_A0
#define ORDER_PP_CM_OUTPUT_CLOSE_B0

#define ORDER_PP_CM_EMIT(P,m,p,r) r ORDER_PP_CM_EMIT_##m P##p

#define ORDER_PP_CM_EMIT_A(P,m,...) ORDER_PP_CM_EMIT_##m(,B,P##__VA_ARGS__)
#define ORDER_PP_CM_EMIT_B(P,m,...) ORDER_PP_CM_EMIT_##m(,A,P##__VA_ARGS__)
#define ORDER_PP_CM_EMIT_0(...)

#define ORDER_PP_CM_EMIT_1(P,_0) P##_0
#define ORDER_PP_CM_EMIT_2(P,_0,_1) P##_0 P##_1
#define ORDER_PP_CM_EMIT_3(P,_0,_1,_2) P##_0 P##_1 P##_2
#define ORDER_PP_CM_EMIT_4(P,_0,_1,_2,_3) P##_0 P##_1 P##_2 P##_3
#define ORDER_PP_CM_EMIT_5(P,_0,_1,_2,_3,_4) P##_0 P##_1 P##_2 P##_3 P##_4
#define ORDER_PP_CM_EMIT_6(P,_0,_1,_2,_3,_4,_5) P##_0 P##_1 P##_2 P##_3 P##_4 P##_5
#define ORDER_PP_CM_EMIT_7(P,_0,_1,_2,_3,_4,_5,_6) P##_0 P##_1 P##_2 P##_3 P##_4 P##_5 P##_6
#define ORDER_PP_CM_EMIT_8(P,_0,_1,_2,_3,_4,_5,_6,_7) P##_0 P##_1 P##_2 P##_3 P##_4 P##_5 P##_6 P##_7
#define ORDER_PP_CM_EMIT_1C(P,_0) P##_0
#define ORDER_PP_CM_EMIT_2C(P,_0,_1) _0##_1
#define ORDER_PP_CM_EMIT_3C(P,_0,_1,_2) _0##_1##_2
#define ORDER_PP_CM_EMIT_4C(P,_0,_1,_2,_3) _0##_1##_2##_3
#define ORDER_PP_CM_EMIT_5C(P,_0,_1,_2,_3,_4) _0##_1##_2##_3##_4
#define ORDER_PP_CM_EMIT_6C(P,_0,_1,_2,_3,_4,_5) _0##_1##_2##_3##_4##_5
#define ORDER_PP_CM_EMIT_7C(P,_0,_1,_2,_3,_4,_5,_6) _0##_1##_2##_3##_4##_5##_6
#define ORDER_PP_CM_EMIT_8C(P,_0,_1,_2,_3,_4,_5,_6,_7) _0##_1##_2##_3##_4##_5##_6##_7

#define ORDER_PP_CM_SCAN_1(P,x,...) x##P __VA_ARGS__
#define ORDER_PP_CM_SCAN_2(P,x,...) x##P __VA_ARGS__
#define ORDER_PP_CM_SCAN_3(P,x,...) x##P __VA_ARGS__
#define ORDER_PP_CM_SCAN_4(P,x,...) x##P __VA_ARGS__
#define ORDER_PP_CM_SCAN_5(P,x,...) x##P __VA_ARGS__
#define ORDER_PP_CM_SCAN_6(P,x,...) x##P __VA_ARGS__
#define ORDER_PP_CM_SCAN_7(P,x,...) x##P __VA_ARGS__
#define ORDER_PP_CM_SCAN_8(P,x,...) x##P __VA_ARGS__

#define ORDER_PP_CM_FIND ORDER_PP_CM_IS_SCAN_ACTIVE(1)(,ORDER_PP_CM_FIND_SCAN_2,ORDER_PP_CM_WAIT_SCAN)(,1)
#define ORDER_PP_CM_FIND_SCAN_2(...) ORDER_PP_CM_IS_SCAN_ACTIVE(2)(,ORDER_PP_CM_FIND_SCAN_3,ORDER_PP_CM_WAIT_SCAN)(,2)
#define ORDER_PP_CM_FIND_SCAN_3(...) ORDER_PP_CM_IS_SCAN_ACTIVE(3)(,ORDER_PP_CM_FIND_SCAN_4,ORDER_PP_CM_WAIT_SCAN)(,3)
#define ORDER_PP_CM_FIND_SCAN_4(...) ORDER_PP_CM_IS_SCAN_ACTIVE(4)(,ORDER_PP_CM_FIND_SCAN_5,ORDER_PP_CM_WAIT_SCAN)(,4)
#define ORDER_PP_CM_FIND_SCAN_5(...) ORDER_PP_CM_IS_SCAN_ACTIVE(5)(,ORDER_PP_CM_FIND_SCAN_6,ORDER_PP_CM_WAIT_SCAN)(,5)
#define ORDER_PP_CM_FIND_SCAN_6(...) ORDER_PP_CM_IS_SCAN_ACTIVE(6)(,ORDER_PP_CM_FIND_SCAN_7,ORDER_PP_CM_WAIT_SCAN)(,6)
#define ORDER_PP_CM_FIND_SCAN_7(...) ORDER_PP_CM_IS_SCAN_ACTIVE(7)(,ORDER_PP_CM_FIND_SCAN_8,ORDER_PP_CM_WAIT_SCAN)(,7)
#define ORDER_PP_CM_FIND_SCAN_8(...) ORDER_PP_CM_IS_SCAN_ACTIVE(8)(,ORDER_PP_CM_FIND_SCAN_9,ORDER_PP_CM_WAIT_SCAN)(,8)
#define ORDER_PP_CM_FIND_SCAN_9() 8ERROR_CM_RECURSION_TOO_DEEP

#define ORDER_PP_CM_WAIT_SCAN(P,i) ORDER_PP_CM_IS_SCAN_ACTIVE(P##i)(,ORDER_PP_CM_WAIT_SCAN_END,ORDER_PP_CM_WAIT_SCAN_B ORDER_PP_EAT())(,P##i)
#define ORDER_PP_CM_WAIT_SCAN_B(P,i) ORDER_PP_CM_IS_SCAN_ACTIVE(P##i)(,ORDER_PP_CM_WAIT_SCAN_END,ORDER_PP_CM_WAIT_SCAN ORDER_PP_EAT())(,P##i)
#define ORDER_PP_CM_WAIT_SCAN_END(P,i) ORDER_PP_CM_##i

#define ORDER_PP_CM_IS_SCAN_ACTIVE(i) ORDER_PP_TEST(,ORDER_PP_CM_SCAN_##i(,,,),ORDER_PP_IF_8false,ORDER_PP_IF_8true)

#define ORDER_PP_CM_8EXIT(P,x,...) ,x##P)

#define ORDER_PP_CM_D_0(...) ORDER_PP_CM_DN_0 __VA_ARGS__
#define ORDER_PP_CM_U_0(...) ORDER_PP_CM_UP_1 __VA_ARGS__
#define ORDER_PP_CM_D_1(...) ORDER_PP_CM_DN_1 __VA_ARGS__
#define ORDER_PP_CM_U_1(...) ORDER_PP_CM_UP_2 __VA_ARGS__
#define ORDER_PP_CM_D_2(...) ORDER_PP_CM_DN_2 __VA_ARGS__
#define ORDER_PP_CM_U_2(...) ORDER_PP_CM_UP_3 __VA_ARGS__
#define ORDER_PP_CM_D_3(...) ORDER_PP_CM_DN_3 __VA_ARGS__
#define ORDER_PP_CM_U_3(...) ORDER_PP_CM_UP_4 __VA_ARGS__
#define ORDER_PP_CM_D_4(...) ORDER_PP_CM_DN_4 __VA_ARGS__
#define ORDER_PP_CM_U_4(...) ORDER_PP_CM_UP_5 __VA_ARGS__
#define ORDER_PP_CM_D_5(...) ORDER_PP_CM_DN_5 __VA_ARGS__
#define ORDER_PP_CM_U_5(...) ORDER_PP_CM_UP_6 __VA_ARGS__
#define ORDER_PP_CM_D_6(...) ORDER_PP_CM_DN_6 __VA_ARGS__
#define ORDER_PP_CM_U_6(...) ORDER_PP_CM_UP_7 __VA_ARGS__
#define ORDER_PP_CM_D_7(...) ORDER_PP_CM_DN_7 __VA_ARGS__
#define ORDER_PP_CM_U_7(...) ORDER_PP_CM_UP_8 __VA_ARGS__
#define ORDER_PP_CM_D_8(...) ORDER_PP_CM_DN_8 __VA_ARGS__
#define ORDER_PP_CM_U_8(...) ORDER_PP_CM_UP_9 __VA_ARGS__
#define ORDER_PP_CM_D_9(...) ORDER_PP_CM_DN_9 __VA_ARGS__
#define ORDER_PP_CM_U_9(...) ORDER_PP_CM_UP_10 __VA_ARGS__
#define ORDER_PP_CM_D_10(...) ORDER_PP_CM_DN_10 __VA_ARGS__
#define ORDER_PP_CM_U_10(...) ORDER_PP_CM_UP_11 __VA_ARGS__
#define ORDER_PP_CM_D_11(...) ORDER_PP_CM_DN_11 __VA_ARGS__
#define ORDER_PP_CM_U_11(...) ORDER_PP_CM_UP_12 __VA_ARGS__
#define ORDER_PP_CM_D_12(...) ORDER_PP_CM_DN_12 __VA_ARGS__
#define ORDER_PP_CM_U_12(...) ORDER_PP_CM_UP_13 __VA_ARGS__
#define ORDER_PP_CM_D_13(...) ORDER_PP_CM_DN_13 __VA_ARGS__
#define ORDER_PP_CM_U_13(...) ORDER_PP_CM_UP_14 __VA_ARGS__
#define ORDER_PP_CM_D_14(...) ORDER_PP_CM_DN_14 __VA_ARGS__
#define ORDER_PP_CM_U_14(...) ORDER_PP_CM_UP_15 __VA_ARGS__
#define ORDER_PP_CM_D_15(...) ORDER_PP_CM_DN_15 __VA_ARGS__
#define ORDER_PP_CM_U_15(...) ORDER_PP_CM_UP_16 __VA_ARGS__
#define ORDER_PP_CM_D_16(...) ORDER_PP_CM_DN_16 __VA_ARGS__
#define ORDER_PP_CM_U_16(...) ORDER_PP_CM_UP_17 __VA_ARGS__
#define ORDER_PP_CM_D_17(...) ORDER_PP_CM_DN_17 __VA_ARGS__
#define ORDER_PP_CM_U_17(...) ORDER_PP_CM_UP_18 __VA_ARGS__
#define ORDER_PP_CM_D_18(...) ORDER_PP_CM_DN_18 __VA_ARGS__
#define ORDER_PP_CM_U_18(...) ORDER_PP_CM_UP_19 __VA_ARGS__
#define ORDER_PP_CM_D_19(...) ORDER_PP_CM_DN_19 __VA_ARGS__
#define ORDER_PP_CM_U_19(...) ORDER_PP_CM_UP_20 __VA_ARGS__
#define ORDER_PP_CM_D_20(...) ORDER_PP_CM_DN_20 __VA_ARGS__
#define ORDER_PP_CM_U_20(...) ORDER_PP_CM_UP_21 __VA_ARGS__
#define ORDER_PP_CM_D_21(...) ORDER_PP_CM_DN_21 __VA_ARGS__
#define ORDER_PP_CM_U_21(...) ORDER_PP_CM_UP_22 __VA_ARGS__
#define ORDER_PP_CM_D_22(...) ORDER_PP_CM_DN_22 __VA_ARGS__
#define ORDER_PP_CM_U_22(...) ORDER_PP_CM_UP_23 __VA_ARGS__
#define ORDER_PP_CM_D_23(...) ORDER_PP_CM_DN_23 __VA_ARGS__
#define ORDER_PP_CM_U_23(...) ORDER_PP_CM_UP_24 __VA_ARGS__
#define ORDER_PP_CM_D_24(...) ORDER_PP_CM_DN_24 __VA_ARGS__
#define ORDER_PP_CM_U_24(...) ORDER_PP_CM_UP_25 __VA_ARGS__
#define ORDER_PP_CM_D_25(...) ORDER_PP_CM_DN_25 __VA_ARGS__
#define ORDER_PP_CM_U_25(...) ORDER_PP_CM_UP_26 __VA_ARGS__
#define ORDER_PP_CM_D_26(...) ORDER_PP_CM_DN_26 __VA_ARGS__
#define ORDER_PP_CM_U_26(...) ORDER_PP_CM_UP_27 __VA_ARGS__
#define ORDER_PP_CM_D_27(...) ORDER_PP_CM_DN_27 __VA_ARGS__
#define ORDER_PP_CM_U_27(...) ORDER_PP_CM_UP_28 __VA_ARGS__
#define ORDER_PP_CM_D_28(...) ORDER_PP_CM_DN_28 __VA_ARGS__
#define ORDER_PP_CM_U_28(...) ORDER_PP_CM_UP_29 __VA_ARGS__
#define ORDER_PP_CM_D_29(...) ORDER_PP_CM_DN_29 __VA_ARGS__
#define ORDER_PP_CM_U_29(...) ORDER_PP_CM_UP_30 __VA_ARGS__
#define ORDER_PP_CM_D_30(...) ORDER_PP_CM_DN_30 __VA_ARGS__
#define ORDER_PP_CM_U_30(...) ORDER_PP_CM_UP_31 __VA_ARGS__

#define ORDER_PP_CM_DN_0(P,x,f,...) ORDER_PP_CM_##f(,x##P,P##__VA_ARGS__)
#define ORDER_PP_CM_UP_0(P,x,f,...) ORDER_PP_CM_U_0(ORDER_PP_CM_U_0(ORDER_PP_CM_D_0(ORDER_PP_CM_##f(,x##P,P##__VA_ARGS__##P))))
#define ORDER_PP_CM_DN_1(P,x,f,...) ORDER_PP_CM_D_0(ORDER_PP_CM_D_0(ORDER_PP_CM_##f(,x##P,P##__VA_ARGS__)))
#define ORDER_PP_CM_UP_1(P,x,f,...) ORDER_PP_CM_U_1(ORDER_PP_CM_U_1(ORDER_PP_CM_D_1(ORDER_PP_CM_##f(,x##P,P##__VA_ARGS__))))
#define ORDER_PP_CM_DN_2(P,x,f,...) ORDER_PP_CM_D_1(ORDER_PP_CM_D_1(ORDER_PP_CM_##f(,x##P,P##__VA_ARGS__)))
#define ORDER_PP_CM_UP_2(P,x,f,...) ORDER_PP_CM_U_2(ORDER_PP_CM_U_2(ORDER_PP_CM_D_2(ORDER_PP_CM_##f(,x##P,P##__VA_ARGS__))))
#define ORDER_PP_CM_DN_3(P,x,f,...) ORDER_PP_CM_D_2(ORDER_PP_CM_D_2(ORDER_PP_CM_##f(,x##P,P##__VA_ARGS__)))
#define ORDER_PP_CM_UP_3(P,x,f,...) ORDER_PP_CM_U_3(ORDER_PP_CM_U_3(ORDER_PP_CM_D_3(ORDER_PP_CM_##f(,x##P,P##__VA_ARGS__))))
#define ORDER_PP_CM_DN_4(P,x,f,...) ORDER_PP_CM_D_3(ORDER_PP_CM_D_3(ORDER_PP_CM_##f(,x##P,P##__VA_ARGS__)))
#define ORDER_PP_CM_UP_4(P,x,f,...) ORDER_PP_CM_U_4(ORDER_PP_CM_U_4(ORDER_PP_CM_D_4(ORDER_PP_CM_##f(,x##P,P##__VA_ARGS__))))
#define ORDER_PP_CM_DN_5(P,x,f,...) ORDER_PP_CM_D_4(ORDER_PP_CM_D_4(ORDER_PP_CM_##f(,x##P,P##__VA_ARGS__)))
#define ORDER_PP_CM_UP_5(P,x,f,...) ORDER_PP_CM_U_5(ORDER_PP_CM_U_5(ORDER_PP_CM_D_5(ORDER_PP_CM_##f(,x##P,P##__VA_ARGS__))))
#define ORDER_PP_CM_DN_6(P,x,f,...) ORDER_PP_CM_D_5(ORDER_PP_CM_D_5(ORDER_PP_CM_##f(,x##P,P##__VA_ARGS__)))
#define ORDER_PP_CM_UP_6(P,x,f,...) ORDER_PP_CM_U_6(ORDER_PP_CM_U_6(ORDER_PP_CM_D_6(ORDER_PP_CM_##f(,x##P,P##__VA_ARGS__))))
#define ORDER_PP_CM_DN_7(P,x,f,...) ORDER_PP_CM_D_6(ORDER_PP_CM_D_6(ORDER_PP_CM_##f(,x##P,P##__VA_ARGS__)))
#define ORDER_PP_CM_UP_7(P,x,f,...) ORDER_PP_CM_U_7(ORDER_PP_CM_U_7(ORDER_PP_CM_D_7(ORDER_PP_CM_##f(,x##P,P##__VA_ARGS__))))
#define ORDER_PP_CM_DN_8(P,x,f,...) ORDER_PP_CM_D_7(ORDER_PP_CM_D_7(ORDER_PP_CM_##f(,x##P,P##__VA_ARGS__)))
#define ORDER_PP_CM_UP_8(P,x,f,...) ORDER_PP_CM_U_8(ORDER_PP_CM_U_8(ORDER_PP_CM_D_8(ORDER_PP_CM_##f(,x##P,P##__VA_ARGS__))))
#define ORDER_PP_CM_DN_9(P,x,f,...) ORDER_PP_CM_D_8(ORDER_PP_CM_D_8(ORDER_PP_CM_##f(,x##P,P##__VA_ARGS__)))
#define ORDER_PP_CM_UP_9(P,x,f,...) ORDER_PP_CM_U_9(ORDER_PP_CM_U_9(ORDER_PP_CM_D_9(ORDER_PP_CM_##f(,x##P,P##__VA_ARGS__))))
#define ORDER_PP_CM_DN_10(P,x,f,...) ORDER_PP_CM_D_9(ORDER_PP_CM_D_9(ORDER_PP_CM_##f(,x##P,P##__VA_ARGS__)))
#define ORDER_PP_CM_UP_10(P,x,f,...) ORDER_PP_CM_U_10(ORDER_PP_CM_U_10(ORDER_PP_CM_D_10(ORDER_PP_CM_##f(,x##P,P##__VA_ARGS__))))
#define ORDER_PP_CM_DN_11(P,x,f,...) ORDER_PP_CM_D_10(ORDER_PP_CM_D_10(ORDER_PP_CM_##f(,x##P,P##__VA_ARGS__)))
#define ORDER_PP_CM_UP_11(P,x,f,...) ORDER_PP_CM_U_11(ORDER_PP_CM_U_11(ORDER_PP_CM_D_11(ORDER_PP_CM_##f(,x##P,P##__VA_ARGS__))))
#define ORDER_PP_CM_DN_12(P,x,f,...) ORDER_PP_CM_D_11(ORDER_PP_CM_D_11(ORDER_PP_CM_##f(,x##P,P##__VA_ARGS__)))
#define ORDER_PP_CM_UP_12(P,x,f,...) ORDER_PP_CM_U_12(ORDER_PP_CM_U_12(ORDER_PP_CM_D_12(ORDER_PP_CM_##f(,x##P,P##__VA_ARGS__))))
#define ORDER_PP_CM_DN_13(P,x,f,...) ORDER_PP_CM_D_12(ORDER_PP_CM_D_12(ORDER_PP_CM_##f(,x##P,P##__VA_ARGS__)))
#define ORDER_PP_CM_UP_13(P,x,f,...) ORDER_PP_CM_U_13(ORDER_PP_CM_U_13(ORDER_PP_CM_D_13(ORDER_PP_CM_##f(,x##P,P##__VA_ARGS__))))
#define ORDER_PP_CM_DN_14(P,x,f,...) ORDER_PP_CM_D_13(ORDER_PP_CM_D_13(ORDER_PP_CM_##f(,x##P,P##__VA_ARGS__)))
#define ORDER_PP_CM_UP_14(P,x,f,...) ORDER_PP_CM_U_14(ORDER_PP_CM_U_14(ORDER_PP_CM_D_14(ORDER_PP_CM_##f(,x##P,P##__VA_ARGS__))))
#define ORDER_PP_CM_DN_15(P,x,f,...) ORDER_PP_CM_D_14(ORDER_PP_CM_D_14(ORDER_PP_CM_##f(,x##P,P##__VA_ARGS__)))
#define ORDER_PP_CM_UP_15(P,x,f,...) ORDER_PP_CM_U_15(ORDER_PP_CM_U_15(ORDER_PP_CM_D_15(ORDER_PP_CM_##f(,x##P,P##__VA_ARGS__))))
#define ORDER_PP_CM_DN_16(P,x,f,...) ORDER_PP_CM_D_15(ORDER_PP_CM_D_15(ORDER_PP_CM_##f(,x##P,P##__VA_ARGS__)))
#define ORDER_PP_CM_UP_16(P,x,f,...) ORDER_PP_CM_U_16(ORDER_PP_CM_U_16(ORDER_PP_CM_D_16(ORDER_PP_CM_##f(,x##P,P##__VA_ARGS__))))
#define ORDER_PP_CM_DN_17(P,x,f,...) ORDER_PP_CM_D_16(ORDER_PP_CM_D_16(ORDER_PP_CM_##f(,x##P,P##__VA_ARGS__)))
#define ORDER_PP_CM_UP_17(P,x,f,...) ORDER_PP_CM_U_17(ORDER_PP_CM_U_17(ORDER_PP_CM_D_17(ORDER_PP_CM_##f(,x##P,P##__VA_ARGS__))))
#define ORDER_PP_CM_DN_18(P,x,f,...) ORDER_PP_CM_D_17(ORDER_PP_CM_D_17(ORDER_PP_CM_##f(,x##P,P##__VA_ARGS__)))
#define ORDER_PP_CM_UP_18(P,x,f,...) ORDER_PP_CM_U_18(ORDER_PP_CM_U_18(ORDER_PP_CM_D_18(ORDER_PP_CM_##f(,x##P,P##__VA_ARGS__))))
#define ORDER_PP_CM_DN_19(P,x,f,...) ORDER_PP_CM_D_18(ORDER_PP_CM_D_18(ORDER_PP_CM_##f(,x##P,P##__VA_ARGS__)))
#define ORDER_PP_CM_UP_19(P,x,f,...) ORDER_PP_CM_U_19(ORDER_PP_CM_U_19(ORDER_PP_CM_D_19(ORDER_PP_CM_##f(,x##P,P##__VA_ARGS__))))
#define ORDER_PP_CM_DN_20(P,x,f,...) ORDER_PP_CM_D_19(ORDER_PP_CM_D_19(ORDER_PP_CM_##f(,x##P,P##__VA_ARGS__)))
#define ORDER_PP_CM_UP_20(P,x,f,...) ORDER_PP_CM_U_20(ORDER_PP_CM_U_20(ORDER_PP_CM_D_20(ORDER_PP_CM_##f(,x##P,P##__VA_ARGS__))))
#define ORDER_PP_CM_DN_21(P,x,f,...) ORDER_PP_CM_D_20(ORDER_PP_CM_D_20(ORDER_PP_CM_##f(,x##P,P##__VA_ARGS__)))
#define ORDER_PP_CM_UP_21(P,x,f,...) ORDER_PP_CM_U_21(ORDER_PP_CM_U_21(ORDER_PP_CM_D_21(ORDER_PP_CM_##f(,x##P,P##__VA_ARGS__))))
#define ORDER_PP_CM_DN_22(P,x,f,...) ORDER_PP_CM_D_21(ORDER_PP_CM_D_21(ORDER_PP_CM_##f(,x##P,P##__VA_ARGS__)))
#define ORDER_PP_CM_UP_22(P,x,f,...) ORDER_PP_CM_U_22(ORDER_PP_CM_U_22(ORDER_PP_CM_D_22(ORDER_PP_CM_##f(,x##P,P##__VA_ARGS__))))
#define ORDER_PP_CM_DN_23(P,x,f,...) ORDER_PP_CM_D_22(ORDER_PP_CM_D_22(ORDER_PP_CM_##f(,x##P,P##__VA_ARGS__)))
#define ORDER_PP_CM_UP_23(P,x,f,...) ORDER_PP_CM_U_23(ORDER_PP_CM_U_23(ORDER_PP_CM_D_23(ORDER_PP_CM_##f(,x##P,P##__VA_ARGS__))))
#define ORDER_PP_CM_DN_24(P,x,f,...) ORDER_PP_CM_D_23(ORDER_PP_CM_D_23(ORDER_PP_CM_##f(,x##P,P##__VA_ARGS__)))
#define ORDER_PP_CM_UP_24(P,x,f,...) ORDER_PP_CM_U_24(ORDER_PP_CM_U_24(ORDER_PP_CM_D_24(ORDER_PP_CM_##f(,x##P,P##__VA_ARGS__))))
#define ORDER_PP_CM_DN_25(P,x,f,...) ORDER_PP_CM_D_24(ORDER_PP_CM_D_24(ORDER_PP_CM_##f(,x##P,P##__VA_ARGS__)))
#define ORDER_PP_CM_UP_25(P,x,f,...) ORDER_PP_CM_U_25(ORDER_PP_CM_U_25(ORDER_PP_CM_D_25(ORDER_PP_CM_##f(,x##P,P##__VA_ARGS__))))
#define ORDER_PP_CM_DN_26(P,x,f,...) ORDER_PP_CM_D_25(ORDER_PP_CM_D_25(ORDER_PP_CM_##f(,x##P,P##__VA_ARGS__)))
#define ORDER_PP_CM_UP_26(P,x,f,...) ORDER_PP_CM_U_26(ORDER_PP_CM_U_26(ORDER_PP_CM_D_26(ORDER_PP_CM_##f(,x##P,P##__VA_ARGS__))))
#define ORDER_PP_CM_DN_27(P,x,f,...) ORDER_PP_CM_D_26(ORDER_PP_CM_D_26(ORDER_PP_CM_##f(,x##P,P##__VA_ARGS__)))
#define ORDER_PP_CM_UP_27(P,x,f,...) ORDER_PP_CM_U_27(ORDER_PP_CM_U_27(ORDER_PP_CM_D_27(ORDER_PP_CM_##f(,x##P,P##__VA_ARGS__))))
#define ORDER_PP_CM_DN_28(P,x,f,...) ORDER_PP_CM_D_27(ORDER_PP_CM_D_27(ORDER_PP_CM_##f(,x##P,P##__VA_ARGS__)))
#define ORDER_PP_CM_UP_28(P,x,f,...) ORDER_PP_CM_U_28(ORDER_PP_CM_U_28(ORDER_PP_CM_D_28(ORDER_PP_CM_##f(,x##P,P##__VA_ARGS__))))
#define ORDER_PP_CM_DN_29(P,x,f,...) ORDER_PP_CM_D_28(ORDER_PP_CM_D_28(ORDER_PP_CM_##f(,x##P,P##__VA_ARGS__)))
#define ORDER_PP_CM_UP_29(P,x,f,...) ORDER_PP_CM_U_29(ORDER_PP_CM_U_29(ORDER_PP_CM_D_29(ORDER_PP_CM_##f(,x##P,P##__VA_ARGS__))))
#define ORDER_PP_CM_DN_30(P,x,f,...) ORDER_PP_CM_D_29(ORDER_PP_CM_D_29(ORDER_PP_CM_##f(,x##P,P##__VA_ARGS__)))
#define ORDER_PP_CM_UP_30(P,x,f,...) ORDER_PP_CM_U_30(ORDER_PP_CM_U_30(ORDER_PP_CM_D_30(ORDER_PP_CM_##f(,x##P,P##__VA_ARGS__))))
#define ORDER_PP_CM_UP_31(P,x,f,...) ORDER_PP_CM_##f(,x##P,P##__VA_ARGS__)

#endif
