// (C) Copyright Vesa Karvonen 2004.
//
// Distributed under the Boost Software License, Version 1.0.
// (See accompanying file LICENSE.)

#define ORDER_PP_OUTPUT(s) ORDER_PP_FX(OUTPUT_EMIT_A,ORDER_PP_CM(,ORDER_PP_OUTPUT_PAIR_A (,0,)s(0,),8OUTPUT_STOP,)))

#define ORDER_PP_8OUTPUT_PAIR(P,s,...) (,ORDER_PP_OUTPUT_PAIR_A P##s(0,),8OUTPUT_SWAP,P##__VA_ARGS__)

#define ORDER_PP_OUTPUT_PAIR_A(P,...) (,(,__VA_ARGS__##P)ORDER_PP_OUTPUT_PAIR_B
#define ORDER_PP_OUTPUT_PAIR_B(P,...) ,ORDER_PP_EAT_UNLESS_##P(,__VA_ARGS__##P))ORDER_PP_OUTPUT_PAIR_C##P
#define ORDER_PP_OUTPUT_PAIR_C(P,...) ORDER_PP_OUTPUT_F##P(,__VA_ARGS__##P)ORDER_PP_OUTPUT_PAIR_D##P
#define ORDER_PP_OUTPUT_PAIR_C0
#define ORDER_PP_OUTPUT_PAIR_D(P,...) ,ORDER_PP_EAT_UNLESS_##P(,__VA_ARGS__##P))ORDER_PP_OUTPUT_PAIR_E##P
#define ORDER_PP_OUTPUT_PAIR_D0
#define ORDER_PP_OUTPUT_PAIR_E(P,...) ORDER_PP_OUTPUT_F##P(,__VA_ARGS__##P)ORDER_PP_OUTPUT_PAIR_F##P
#define ORDER_PP_OUTPUT_PAIR_E0 ,8OUTPUT_PAIR
#define ORDER_PP_OUTPUT_PAIR_F(P,...) ,ORDER_PP_EAT_UNLESS_##P(,__VA_ARGS__##P))ORDER_PP_OUTPUT_PAIR_E##P
#define ORDER_PP_OUTPUT_PAIR_F0 ,8OUTPUT_PAIR

#define ORDER_PP_OUTPUT_F (,
#define ORDER_PP_OUTPUT_F0(...)

#define ORDER_PP_8OUTPUT_SWAP(P,s,...) (,ORDER_PP_OUTPUT_SWAP_A P##s,P##__VA_ARGS__)

#define ORDER_PP_OUTPUT_SWAP_A(P,x,y) P##y P##x ORDER_PP_OUTPUT_SWAP_B
#define ORDER_PP_OUTPUT_SWAP_B(P,x,y) P##y P##x ORDER_PP_OUTPUT_SWAP_A

#define ORDER_PP_8OUTPUT_STOP(P,s,...) )ORDER_PP_OUTPUT_SWAP_A P##s

#define ORDER_PP_OUTPUT_EMIT_A(P,m,...) ORDER_PP_OUTPUT_EMIT_##m(,__VA_ARGS__##P)ORDER_PP_OUTPUT_EMIT_B
#define ORDER_PP_OUTPUT_EMIT_B(P,m,...) ORDER_PP_OUTPUT_EMIT_##m(,__VA_ARGS__##P)ORDER_PP_OUTPUT_EMIT_A

#define ORDER_PP_OUTPUT_EMIT_0 ORDER_PP_EAT(
#define ORDER_PP_OUTPUT_EMIT_1(P,...) P##__VA_ARGS__
#define ORDER_PP_OUTPUT_EMIT_2(P,m,...) m##P ORDER_PP_NIL()P##__VA_ARGS__
#define ORDER_PP_OUTPUT_EMIT_3(P,...) ,P##__VA_ARGS__
#define ORDER_PP_OUTPUT_EMIT_4(P,...) (P##__VA_ARGS__
#define ORDER_PP_OUTPUT_EMIT_5(P,...) )P##__VA_ARGS__
