#ifndef ORDER_OUTPUT_H_VAJK20040620
#define ORDER_OUTPUT_H_VAJK20040620

// (C) Copyright Vesa Karvonen 2004.
//
//    Distributed under the Boost Software License, Version 1.0.

#include "order/util.h"

#define ORDER_PP_OUTPUT(s) ORDER_PP_OUTPUT_EMIT_A ORDER_PP_OUTPUT_SCAN(ORDER_PP_OUTPUT_REV_OUT_A(9,)s(9,)(0,))(0,0,)
#define ORDER_PP_OUTPUT_SCAN(x) x

#define ORDER_PP_OUTPUT_REV_OUT_A(P,...) ORDER_PP_OUTPUT_REV_OUT##P(,__VA_ARGS__##P)ORDER_PP_OUTPUT_REV_OUT_B##P
#define ORDER_PP_OUTPUT_REV_OUT_A0
#define ORDER_PP_OUTPUT_REV_OUT_A9 (,ORDER_PP_OUTPUT_REV_IN_B
#define ORDER_PP_OUTPUT_REV_OUT_B(P,...) ORDER_PP_OUTPUT_REV_OUT##P(,__VA_ARGS__##P)ORDER_PP_OUTPUT_REV_OUT_A##P
#define ORDER_PP_OUTPUT_REV_OUT_B0
#define ORDER_PP_OUTPUT_REV_OUT_B9 (,ORDER_PP_OUTPUT_REV_IN_A
#define ORDER_PP_OUTPUT_REV_OUT0(...)
#define ORDER_PP_OUTPUT_REV_OUT9(...) ORDER_PP_OUTPUT_REVERSE
#define ORDER_PP_OUTPUT_REV_OUT

#define ORDER_PP_OUTPUT_REV_IN_A(P,...) ORDER_PP_OUTPUT_REV_IN##P(,__VA_ARGS__##P)ORDER_PP_OUTPUT_REV_IN_B##P
#define ORDER_PP_OUTPUT_REV_IN_A0
#define ORDER_PP_OUTPUT_REV_IN_A9 )ORDER_PP_OUTPUT_REV_OUT_B
#define ORDER_PP_OUTPUT_REV_IN_B(P,...) ORDER_PP_OUTPUT_REV_IN##P(,__VA_ARGS__##P)ORDER_PP_OUTPUT_REV_IN_A##P
#define ORDER_PP_OUTPUT_REV_IN_B0
#define ORDER_PP_OUTPUT_REV_IN_B9 )ORDER_PP_OUTPUT_REV_OUT_A
#define ORDER_PP_OUTPUT_REV_IN0(...) ORDER_PP_ERROR_ODD_NUMBER_OF_OUTPUT_REVERSAL_TOGGLES(!)
#define ORDER_PP_OUTPUT_REV_IN9(...)
#define ORDER_PP_OUTPUT_REV_IN

#define ORDER_PP_ERROR_ODD_NUMBER_OF_OUTPUT_REVERSAL_TOGGLES()

#define ORDER_PP_OUTPUT_REVERSE(P,s) ORDER_PP_PM(,ORDER_PP_OUTPUT_REV_PAIR_A P##s(0,),8OUTPUT_REV_PAIR,0,)
#define ORDER_PP_8OUTPUT_REV_PAIR(P,s,n,...) ORDER_PP_IS_SEQ_SIZE_LESS_EQ_1(,P##s)(ORDER_PP_,8OUTPUT_REV_SWAP,8OUTPUT_REV_PAIR_CONT)(,P##s,P##n,)
#define ORDER_PP_8OUTPUT_REV_PAIR_CONT(P,s,n,...) (,ORDER_PP_OUTPUT_REV_PAIR_A P##s(0,),8OUTPUT_REV_PAIR,ORDER_PP_INC_##n,)
#define ORDER_PP_OUTPUT_REV_PAIR_A(P,...) ORDER_PP_OUTPUT_REV_PAIR_B##P(,__VA_ARGS__##P)
#define ORDER_PP_OUTPUT_REV_PAIR_B(P,...) (,(,P##__VA_ARGS__),ORDER_PP_OUTPUT_REV_PAIR_C
#define ORDER_PP_OUTPUT_REV_PAIR_B0(...)
#define ORDER_PP_OUTPUT_REV_PAIR_C(P,...) ORDER_PP_OUTPUT_REV_PAIR_D##P(,__VA_ARGS__##P)
#define ORDER_PP_OUTPUT_REV_PAIR_D(P,...) (,P##__VA_ARGS__))ORDER_PP_OUTPUT_REV_PAIR_A
#define ORDER_PP_OUTPUT_REV_PAIR_D0(...) )
#define ORDER_PP_8OUTPUT_REV_SWAP(P,s,n,...) ORDER_PP_IS_0_##n(,ORDER_PP_8EXIT,)(,ORDER_PP_SEQ_TERMINATE(ORDER_PP_OUTPUT_REV_SWAP_A P##s),8OUTPUT_REV_SWAP,ORDER_PP_DEC_##n,)
#define ORDER_PP_OUTPUT_REV_SWAP_A(P,x,y) P##y P##x ORDER_PP_OUTPUT_REV_SWAP_B
#define ORDER_PP_OUTPUT_REV_SWAP_A0
#define ORDER_PP_OUTPUT_REV_SWAP_B(P,x,y) P##y P##x ORDER_PP_OUTPUT_REV_SWAP_A
#define ORDER_PP_OUTPUT_REV_SWAP_B0

#define ORDER_PP_OUTPUT_EMIT_A(P,m,...) ORDER_PP_OUTPUT_EMIT_##m(,P##__VA_ARGS__)ORDER_PP_OUTPUT_EMIT_B##P
#define ORDER_PP_OUTPUT_EMIT_A0
#define ORDER_PP_OUTPUT_EMIT_B(P,m,...) ORDER_PP_OUTPUT_EMIT_##m(,P##__VA_ARGS__)ORDER_PP_OUTPUT_EMIT_A##P
#define ORDER_PP_OUTPUT_EMIT_B0

#define ORDER_PP_OUTPUT_EMIT_0(...)
#define ORDER_PP_OUTPUT_EMIT_1(P,...) __VA_ARGS__##P
#define ORDER_PP_OUTPUT_EMIT_2(P,m,...) m##P ORDER_PP_BLOCK __VA_ARGS__##P
#define ORDER_PP_OUTPUT_EMIT_3(P,...) ,__VA_ARGS__##P
#define ORDER_PP_OUTPUT_EMIT_4(P,...) (__VA_ARGS__##P
#define ORDER_PP_OUTPUT_EMIT_5(P,...) )__VA_ARGS__##P

#endif
