#!/bin/bash

# (C) Copyright Vesa Karvonen 2004.
#
# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file LICENSE.)

set -e

./Test "$@" $(find -maxdepth 1 -name '*.c' -o -name '*.cpp' | sort -r)
