#!/bin/bash

# (C) Copyright Vesa Karvonen 2004.
#
# Distributed under the Boost Software License, Version 1.0.

for f in *.h *.hpp *.c *.cpp ; do
    if test -f "$f" ; then
        ./test "$f"
    fi
done
