#!/bin/bash

# (C) Copyright Vesa Karvonen 2004.
#
# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file LICENSE.)

doc=tom

function newest {
    if test 0 -lt "$#" ; then
        result="$1"

        shift

        while test 0 -lt "$#" ; do
            if test "$1" -nt "$result" ; then
                result="$1"
            fi
            shift
        done

        echo "$result"
    fi
}

REPLY=''
prompt='[ (R)ebuild | (Q)uit ]: '

while test "$REPLY" != 'q' ; do
    if test "$REPLY" == 'r' -o $(newest "$doc.ltx" *.ebnf ../../example/*.c* ../../example/*.h*) -nt "$doc.ps" ; then
        echo
        ./Build
        prompt='[ (R)ebuild | (Q)uit ]: '
        REPLY=''
    fi
    read -t 10 -n 1 -p "$prompt"
    prompt=''
done
echo
