// (C) Copyright Vesa Karvonen 2004.
//
// Distributed under the Boost Software License, Version 1.0.

#define ORDER_PP_DEF_8apply ORDER_PP_FN_NATIVE(2,9APPLY)
#define ORDER_PP_9APPLY(P,f,ps) ORDER_PP_FX(TUPLE_AT_0,(,ORDER_PP_REM ps##P,)),ORDER_PP_OPEN f##P ORDER_PP_FX(IS_TUPLE_SIZE_1,(,ORDER_PP_REM ps##P))(,,,8APPLY_LOOP,(,ORDER_PP_FX(TUPLE_REST,(,ORDER_PP_REM ps##P))))
#define ORDER_PP_8APPLY_LOOP(P,f,ps,...) (,ORDER_PP_FX(TUPLE_AT_0,(,ORDER_PP_OPEN ps##P,)),ORDER_PP_OPEN f##P,ORDER_PP_IS_TUPLE_SIZE_1 ps##P(,,8APPLY_LOOP,(,ORDER_PP_TUPLE_REST ps##P),)P##__VA_ARGS__)

#define ORDER_PP_DEF_8chain ORDER_PP_OP_LEFT_NATIVE(9COMPOSE)

#define ORDER_PP_DEF_8compose ORDER_PP_FN_NATIVE(2,9COMPOSE)
#define ORDER_PP_9COMPOSE(P,f,g) (,ORDER_PP_OPEN g##P,ORDER_PP_OPEN f##P)

#define ORDER_PP_DEF_8identity ORDER_PP_FN_NATIVE(1,9IDENTITY)
#define ORDER_PP_9IDENTITY(P,x) P##x

#define ORDER_PP_DEF_8ignore ORDER_PP_FN_NATIVE(1,9IGNORE)
#define ORDER_PP_9IGNORE(...)
