#ifndef ORDER_PRELUDE_NAT_H_VAJK20040620
#define ORDER_PRELUDE_NAT_H_VAJK20040620

// (C) Copyright Vesa Karvonen 2004.
//
//    Distributed under the Boost Software License, Version 1.0.

#define ORDER_PP_DEF_8nat(...) 8NAT,ORDER_PP_PTUPLE_SIZE(,0##__VA_ARGS__),(,0##__VA_ARGS__)
#define ORDER_PP_CM_8NAT(P,e,n,d,...) (,ORDER_PP_NAT_##n d##P,P##__VA_ARGS__)
#define ORDER_PP_NAT(...) ORDER_PP_CAT(ORDER_PP_NAT_,ORDER_PP_PTUPLE_SIZE(,0##__VA_ARGS__))(,0##__VA_ARGS__)
#define ORDER_PP_NAT_1(P,_0) (P##_0)
#define ORDER_PP_NAT_2(P,_0,_1) (P##_1)(P##_0)
#define ORDER_PP_NAT_3(P,_0,_1,_2) (P##_2)(P##_1)(P##_0)
#define ORDER_PP_NAT_4(P,_0,_1,_2,_3) (P##_3)(P##_2)(P##_1)(P##_0)
#define ORDER_PP_NAT_5(P,_0,_1,_2,_3,_4) (P##_4)(P##_3)(P##_2)(P##_1)(P##_0)
#define ORDER_PP_NAT_6(P,_0,_1,_2,_3,_4,_5) (P##_5)(P##_4)(P##_3)(P##_2)(P##_1)(P##_0)
#define ORDER_PP_NAT_7(P,_0,_1,_2,_3,_4,_5,_6) (P##_6)(P##_5)(P##_4)(P##_3)(P##_2)(P##_1)(P##_0)
#define ORDER_PP_NAT_8(P,_0,_1,_2,_3,_4,_5,_6,_7) (P##_7)(P##_6)(P##_5)(P##_4)(P##_3)(P##_2)(P##_1)(P##_0)
#define ORDER_PP_NAT_9(P,_0,_1,_2,_3,_4,_5,_6,_7,_8) (P##_8)(P##_7)(P##_6)(P##_5)(P##_4)(P##_3)(P##_2)(P##_1)(P##_0)
#define ORDER_PP_NAT_10(P,_0,_1,_2,_3,_4,_5,_6,_7,_8,_9) (P##_9)(P##_8)(P##_7)(P##_6)(P##_5)(P##_4)(P##_3)(P##_2)(P##_1)(P##_0)

#define ORDER_PP_DEF_8succ ORDER_PP_FN_CM(1,8SUCC)
#define ORDER_PP_CM_8SUCC(P,n,...) (,ORDER_PP_SUCC n##P,P##__VA_ARGS__)
#define ORDER_PP_SUCC(d) ORDER_PP_SUCC_##d
#define ORDER_PP_SUCC_0 (1)
#define ORDER_PP_SUCC_1 (2)
#define ORDER_PP_SUCC_2 (3)
#define ORDER_PP_SUCC_3 (4)
#define ORDER_PP_SUCC_4 (5)
#define ORDER_PP_SUCC_5 (6)
#define ORDER_PP_SUCC_6 (7)
#define ORDER_PP_SUCC_7 (8)
#define ORDER_PP_SUCC_8 (9)
#define ORDER_PP_SUCC_9 (0)ORDER_PP_SUCC_B
#define ORDER_PP_SUCC_00 (01)
#define ORDER_PP_SUCC_01 (02)
#define ORDER_PP_SUCC_02 (03)
#define ORDER_PP_SUCC_03 (04)
#define ORDER_PP_SUCC_04 (05)
#define ORDER_PP_SUCC_05 (06)
#define ORDER_PP_SUCC_06 (07)
#define ORDER_PP_SUCC_07 (08)
#define ORDER_PP_SUCC_08 (09)
#define ORDER_PP_SUCC_09 (0)(01)
#define ORDER_PP_SUCC_B(d) ORDER_PP_SUCC_B_##d
#define ORDER_PP_SUCC_B_0 (1)
#define ORDER_PP_SUCC_B_1 (2)
#define ORDER_PP_SUCC_B_2 (3)
#define ORDER_PP_SUCC_B_3 (4)
#define ORDER_PP_SUCC_B_4 (5)
#define ORDER_PP_SUCC_B_5 (6)
#define ORDER_PP_SUCC_B_6 (7)
#define ORDER_PP_SUCC_B_7 (8)
#define ORDER_PP_SUCC_B_8 (9)
#define ORDER_PP_SUCC_B_9 (0)ORDER_PP_SUCC
#define ORDER_PP_SUCC_B_00 (01)
#define ORDER_PP_SUCC_B_01 (02)
#define ORDER_PP_SUCC_B_02 (03)
#define ORDER_PP_SUCC_B_03 (04)
#define ORDER_PP_SUCC_B_04 (05)
#define ORDER_PP_SUCC_B_05 (06)
#define ORDER_PP_SUCC_B_06 (07)
#define ORDER_PP_SUCC_B_07 (08)
#define ORDER_PP_SUCC_B_08 (09)
#define ORDER_PP_SUCC_B_09 (0)(01)

#define ORDER_PP_DEF_8pred ORDER_PP_FN_CM(1,8PRED)
#define ORDER_PP_CM_8PRED(P,n,...) (,ORDER_PP_PRED n##P,P##__VA_ARGS__)
#define ORDER_PP_PRED(d) ORDER_PP_PRED_##d
#define ORDER_PP_PRED_0 ORDER_PP_PRED_A
#define ORDER_PP_PRED_1 (0)
#define ORDER_PP_PRED_2 (1)
#define ORDER_PP_PRED_3 (2)
#define ORDER_PP_PRED_4 (3)
#define ORDER_PP_PRED_5 (4)
#define ORDER_PP_PRED_6 (5)
#define ORDER_PP_PRED_7 (6)
#define ORDER_PP_PRED_8 (7)
#define ORDER_PP_PRED_9 (8)
#define ORDER_PP_PRED_00 (00)
#define ORDER_PP_PRED_01 (00)
#define ORDER_PP_PRED_02 (01)
#define ORDER_PP_PRED_03 (02)
#define ORDER_PP_PRED_04 (03)
#define ORDER_PP_PRED_05 (04)
#define ORDER_PP_PRED_06 (05)
#define ORDER_PP_PRED_07 (06)
#define ORDER_PP_PRED_08 (07)
#define ORDER_PP_PRED_09 (08)
#define ORDER_PP_PRED_A(d) ORDER_PP_PRED_A_##d
#define ORDER_PP_PRED_A_0 (9)ORDER_PP_PRED_B
#define ORDER_PP_PRED_A_1 (9)(0)
#define ORDER_PP_PRED_A_2 (9)(1)
#define ORDER_PP_PRED_A_3 (9)(2)
#define ORDER_PP_PRED_A_4 (9)(3)
#define ORDER_PP_PRED_A_5 (9)(4)
#define ORDER_PP_PRED_A_6 (9)(5)
#define ORDER_PP_PRED_A_7 (9)(6)
#define ORDER_PP_PRED_A_8 (9)(7)
#define ORDER_PP_PRED_A_9 (9)(8)
#define ORDER_PP_PRED_A_01 (09)
#define ORDER_PP_PRED_A_02 (9)(01)
#define ORDER_PP_PRED_A_03 (9)(02)
#define ORDER_PP_PRED_A_04 (9)(03)
#define ORDER_PP_PRED_A_05 (9)(04)
#define ORDER_PP_PRED_A_06 (9)(05)
#define ORDER_PP_PRED_A_07 (9)(06)
#define ORDER_PP_PRED_A_08 (9)(07)
#define ORDER_PP_PRED_A_09 (9)(08)
#define ORDER_PP_PRED_B(d) ORDER_PP_PRED_B_##d
#define ORDER_PP_PRED_B_0 (9)ORDER_PP_PRED_A
#define ORDER_PP_PRED_B_1 (9)(0)
#define ORDER_PP_PRED_B_2 (9)(1)
#define ORDER_PP_PRED_B_3 (9)(2)
#define ORDER_PP_PRED_B_4 (9)(3)
#define ORDER_PP_PRED_B_5 (9)(4)
#define ORDER_PP_PRED_B_6 (9)(5)
#define ORDER_PP_PRED_B_7 (9)(6)
#define ORDER_PP_PRED_B_8 (9)(7)
#define ORDER_PP_PRED_B_9 (9)(8)
#define ORDER_PP_PRED_B_01 (09)
#define ORDER_PP_PRED_B_02 (9)(01)
#define ORDER_PP_PRED_B_03 (9)(02)
#define ORDER_PP_PRED_B_04 (9)(03)
#define ORDER_PP_PRED_B_05 (9)(04)
#define ORDER_PP_PRED_B_06 (9)(05)
#define ORDER_PP_PRED_B_07 (9)(06)
#define ORDER_PP_PRED_B_08 (9)(07)
#define ORDER_PP_PRED_B_09 (9)(08)

#endif
