// (C) Copyright Vesa Karvonen 2004.
//
// Distributed under the Boost Software License, Version 1.0.
// (See accompanying file LICENSE.)

#define ORDER_PP_DEF_8is_tuple ORDER_PP_FN_CM(1,8IS_TUPLE,0IS_ANY)
#define ORDER_PP_8IS_TUPLE(P,t,...) (,ORDER_PP_0IS_TUPLE(,P##t)(,8true,8false),P##__VA_ARGS__)

#define ORDER_PP_DEF_8pair ORDER_PP_FN_CM(2,8PAIR,0IS_ANY,0IS_ANY)
#define ORDER_PP_8PAIR(P,r,l,...) (,(P##l,P##r),P##__VA_ARGS__)

#define ORDER_PP_DEF_8riap ORDER_PP_FN_CM(2,8RIAP,0IS_ANY,0IS_ANY)
#define ORDER_PP_8RIAP(P,l,r,...) (,(P##l,P##r),P##__VA_ARGS__)

#define ORDER_PP_DEF_8tuple_append ORDER_PP_OP_LEFT_NATIVE(9TUPLE_JOIN,0IS_TUPLE)

#define ORDER_PP_DEF_8tuple_at ORDER_PP_FN_NATIVE(2,9TUPLE_AT,0IS_NUM,0IS_TUPLE)
#define ORDER_PP_9TUPLE_AT(P,i,t) ORDER_PP_FX(TUPLE_AT_0,(,ORDER_PP_TUPLE_DROP(,P##i)(,P##i,P##t),))

#define ORDER_PP_DEF_8tuple_at_0 ORDER_PP_FN_CM(1,8TUPLE_AT_0,0IS_TUPLE)
#define ORDER_PP_DEF_8tuple_at_1 ORDER_PP_FN_CM(1,8TUPLE_AT_1,0IS_TUPLE)
#define ORDER_PP_DEF_8tuple_at_2 ORDER_PP_FN_CM(1,8TUPLE_AT_2,0IS_TUPLE)
#define ORDER_PP_DEF_8tuple_at_3 ORDER_PP_FN_CM(1,8TUPLE_AT_3,0IS_TUPLE)
#define ORDER_PP_DEF_8tuple_at_4 ORDER_PP_FN_CM(1,8TUPLE_AT_4,0IS_TUPLE)
#define ORDER_PP_DEF_8tuple_at_5 ORDER_PP_FN_CM(1,8TUPLE_AT_5,0IS_TUPLE)
#define ORDER_PP_DEF_8tuple_at_6 ORDER_PP_FN_CM(1,8TUPLE_AT_6,0IS_TUPLE)
#define ORDER_PP_DEF_8tuple_at_7 ORDER_PP_FN_CM(1,8TUPLE_AT_7,0IS_TUPLE)
#define ORDER_PP_DEF_8tuple_at_8 ORDER_PP_FN_CM(1,8TUPLE_AT_8,0IS_TUPLE)
#define ORDER_PP_DEF_8tuple_at_9 ORDER_PP_FN_CM(1,8TUPLE_AT_9,0IS_TUPLE)

#define ORDER_PP_8TUPLE_AT_0(P,t,...) (,ORDER_PP_FX(TUPLE_AT_0,(,ORDER_PP_REM t##P,)),P##__VA_ARGS__)
#define ORDER_PP_8TUPLE_AT_1(P,t,...) (,ORDER_PP_FX(TUPLE_AT_1,(,ORDER_PP_REM t##P,)),P##__VA_ARGS__)
#define ORDER_PP_8TUPLE_AT_2(P,t,...) (,ORDER_PP_FX(TUPLE_AT_2,(,ORDER_PP_REM t##P,)),P##__VA_ARGS__)
#define ORDER_PP_8TUPLE_AT_3(P,t,...) (,ORDER_PP_FX(TUPLE_AT_3,(,ORDER_PP_REM t##P,)),P##__VA_ARGS__)
#define ORDER_PP_8TUPLE_AT_4(P,t,...) (,ORDER_PP_FX(TUPLE_AT_4,(,ORDER_PP_REM t##P,)),P##__VA_ARGS__)
#define ORDER_PP_8TUPLE_AT_5(P,t,...) (,ORDER_PP_FX(TUPLE_AT_5,(,ORDER_PP_REM t##P,)),P##__VA_ARGS__)
#define ORDER_PP_8TUPLE_AT_6(P,t,...) (,ORDER_PP_FX(TUPLE_AT_6,(,ORDER_PP_REM t##P,)),P##__VA_ARGS__)
#define ORDER_PP_8TUPLE_AT_7(P,t,...) (,ORDER_PP_FX(TUPLE_AT_7,(,ORDER_PP_REM t##P,)),P##__VA_ARGS__)
#define ORDER_PP_8TUPLE_AT_8(P,t,...) (,ORDER_PP_FX(TUPLE_AT_8,(,ORDER_PP_REM t##P,)),P##__VA_ARGS__)
#define ORDER_PP_8TUPLE_AT_9(P,t,...) (,ORDER_PP_FX(TUPLE_AT_9,(,ORDER_PP_REM t##P,)),P##__VA_ARGS__)

#ifdef ORDER_PP_DEBUG
# define ORDER_PP_8TUPLE_AT_1_PRECONDITION(P,t) ORDER_PP_FY(NUM_LESS,(,1,ORDER_PP_FY(TUPLE_SIZE,(,ORDER_PP_REM P##t))))
# define ORDER_PP_8TUPLE_AT_2_PRECONDITION(P,t) ORDER_PP_FY(NUM_LESS,(,2,ORDER_PP_FY(TUPLE_SIZE,(,ORDER_PP_REM P##t))))
# define ORDER_PP_8TUPLE_AT_3_PRECONDITION(P,t) ORDER_PP_FY(NUM_LESS,(,3,ORDER_PP_FY(TUPLE_SIZE,(,ORDER_PP_REM P##t))))
# define ORDER_PP_8TUPLE_AT_4_PRECONDITION(P,t) ORDER_PP_FY(NUM_LESS,(,4,ORDER_PP_FY(TUPLE_SIZE,(,ORDER_PP_REM P##t))))
# define ORDER_PP_8TUPLE_AT_5_PRECONDITION(P,t) ORDER_PP_FY(NUM_LESS,(,5,ORDER_PP_FY(TUPLE_SIZE,(,ORDER_PP_REM P##t))))
# define ORDER_PP_8TUPLE_AT_6_PRECONDITION(P,t) ORDER_PP_FY(NUM_LESS,(,6,ORDER_PP_FY(TUPLE_SIZE,(,ORDER_PP_REM P##t))))
# define ORDER_PP_8TUPLE_AT_7_PRECONDITION(P,t) ORDER_PP_FY(NUM_LESS,(,7,ORDER_PP_FY(TUPLE_SIZE,(,ORDER_PP_REM P##t))))
# define ORDER_PP_8TUPLE_AT_8_PRECONDITION(P,t) ORDER_PP_FY(NUM_LESS,(,8,ORDER_PP_FY(TUPLE_SIZE,(,ORDER_PP_REM P##t))))
# define ORDER_PP_8TUPLE_AT_9_PRECONDITION(P,t) ORDER_PP_FY(NUM_LESS,(,9,ORDER_PP_FY(TUPLE_SIZE,(,ORDER_PP_REM P##t))))
#endif

#define ORDER_PP_DEF_8tuple_drop ORDER_PP_FN_NATIVE(2,9TUPLE_DROP,0IS_NUM,0IS_TUPLE)
#define ORDER_PP_9TUPLE_DROP(P,n,t) (ORDER_PP_TUPLE_DROP(,P##n)(,P##n,P##t))
#define ORDER_PP_TUPLE_DROP(P,n) ORDER_PP_TEST(ORDER_PP_TUPLE_DROP_,ORDER_PP_IS_EDIBLE_TEST P##n,NAT,LIT)
#define ORDER_PP_TUPLE_DROP_LIT(P,n,t) ORDER_PP_FX(TUPLE_DROP_##n,(,ORDER_PP_REM t##P))
#define ORDER_PP_TUPLE_DROP_NAT(P,n,t) ORDER_PP_EXPAND(ORDER_PP_OVERLOAD(TUPLE_DROP,ORDER_PP_SCAN(ORDER_PP_NAT_MOD_100_LIT P##n)),(,ORDER_PP_PM(,ORDER_PP_NAT_DIV_100 P##n,8TUPLE_DROP_100N,(,ORDER_PP_REM t##P),)))

#define ORDER_PP_DEF_8tuple_drop_1 ORDER_PP_FN_CM(1,8TUPLE_DROP_1,0IS_TUPLE)
#define ORDER_PP_DEF_8tuple_drop_2 ORDER_PP_FN_CM(1,8TUPLE_DROP_2,0IS_TUPLE)
#define ORDER_PP_DEF_8tuple_drop_3 ORDER_PP_FN_CM(1,8TUPLE_DROP_3,0IS_TUPLE)
#define ORDER_PP_DEF_8tuple_drop_4 ORDER_PP_FN_CM(1,8TUPLE_DROP_4,0IS_TUPLE)
#define ORDER_PP_DEF_8tuple_drop_5 ORDER_PP_FN_CM(1,8TUPLE_DROP_5,0IS_TUPLE)
#define ORDER_PP_DEF_8tuple_drop_6 ORDER_PP_FN_CM(1,8TUPLE_DROP_6,0IS_TUPLE)
#define ORDER_PP_DEF_8tuple_drop_7 ORDER_PP_FN_CM(1,8TUPLE_DROP_7,0IS_TUPLE)
#define ORDER_PP_DEF_8tuple_drop_8 ORDER_PP_FN_CM(1,8TUPLE_DROP_8,0IS_TUPLE)
#define ORDER_PP_DEF_8tuple_drop_9 ORDER_PP_FN_CM(1,8TUPLE_DROP_9,0IS_TUPLE)

#define ORDER_PP_8TUPLE_DROP_1(P,t,...) (,(ORDER_PP_FX(TUPLE_DROP_1,(,ORDER_PP_REM t##P))),P##__VA_ARGS__)
#define ORDER_PP_8TUPLE_DROP_2(P,t,...) (,(ORDER_PP_FX(TUPLE_DROP_2,(,ORDER_PP_REM t##P))),P##__VA_ARGS__)
#define ORDER_PP_8TUPLE_DROP_3(P,t,...) (,(ORDER_PP_FX(TUPLE_DROP_3,(,ORDER_PP_REM t##P))),P##__VA_ARGS__)
#define ORDER_PP_8TUPLE_DROP_4(P,t,...) (,(ORDER_PP_FX(TUPLE_DROP_4,(,ORDER_PP_REM t##P))),P##__VA_ARGS__)
#define ORDER_PP_8TUPLE_DROP_5(P,t,...) (,(ORDER_PP_FX(TUPLE_DROP_5,(,ORDER_PP_REM t##P))),P##__VA_ARGS__)
#define ORDER_PP_8TUPLE_DROP_6(P,t,...) (,(ORDER_PP_FX(TUPLE_DROP_6,(,ORDER_PP_REM t##P))),P##__VA_ARGS__)
#define ORDER_PP_8TUPLE_DROP_7(P,t,...) (,(ORDER_PP_FX(TUPLE_DROP_7,(,ORDER_PP_REM t##P))),P##__VA_ARGS__)
#define ORDER_PP_8TUPLE_DROP_8(P,t,...) (,(ORDER_PP_FX(TUPLE_DROP_8,(,ORDER_PP_REM t##P))),P##__VA_ARGS__)
#define ORDER_PP_8TUPLE_DROP_9(P,t,...) (,(ORDER_PP_FX(TUPLE_DROP_9,(,ORDER_PP_REM t##P))),P##__VA_ARGS__)

#define ORDER_PP_DEF_8tuple_join ORDER_PP_FN_NATIVE(2,9TUPLE_JOIN,0IS_TUPLE,0IS_TUPLE)
#define ORDER_PP_9TUPLE_JOIN(P,l,r) (ORDER_PP_REM l##P,ORDER_PP_REM r##P)

#define ORDER_PP_DEF_8tuple_push_back ORDER_PP_FN_NATIVE(2,9TUPLE_PUSH_BACK,0IS_ANY,0IS_TUPLE)
#define ORDER_PP_9TUPLE_PUSH_BACK(P,x,t) (ORDER_PP_REM t##P,P##x)

#define ORDER_PP_DEF_8tuple_push_front ORDER_PP_FN_NATIVE(2,9TUPLE_PUSH_FRONT,0IS_ANY,0IS_TUPLE)
#define ORDER_PP_9TUPLE_PUSH_FRONT(P,x,t) (P##x,ORDER_PP_REM t##P)

#define ORDER_PP_DEF_8tuple_size ORDER_PP_FN_CM(1,8TUPLE_SIZE,0IS_TUPLE)
#define ORDER_PP_8TUPLE_SIZE(P,t,...) (,ORDER_PP_FY(TUPLE_SIZE,(,ORDER_PP_REM P##t)),P##__VA_ARGS__)

#define ORDER_PP_TUPLE_SIZE(P,...) ORDER_PP_OVERLOAD(TUPLE_SIZE,ORDER_PP_TUPLE_SIZE_MAX_11_OR_MORE(,P##__VA_ARGS__))(,P##__VA_ARGS__)
#define ORDER_PP_TUPLE_SIZE_1(...) 1
#define ORDER_PP_TUPLE_SIZE_2(...) 2
#define ORDER_PP_TUPLE_SIZE_3(...) 3
#define ORDER_PP_TUPLE_SIZE_4(...) 4
#define ORDER_PP_TUPLE_SIZE_5(...) 5
#define ORDER_PP_TUPLE_SIZE_6(...) 6
#define ORDER_PP_TUPLE_SIZE_7(...) 7
#define ORDER_PP_TUPLE_SIZE_8(...) 8
#define ORDER_PP_TUPLE_SIZE_9(...) 9
#define ORDER_PP_TUPLE_SIZE_10(...) 10
#define ORDER_PP_TUPLE_SIZE_11_OR_MORE(P,_0,_1,_2,_3,_4,_5,_6,_7,_8,_9,...) ORDER_PP_PM(,(,P##__VA_ARGS__),8TUPLE_SIZE_2,(01),)
#define ORDER_PP_8TUPLE_SIZE_2(P,t,n,...) ORDER_PP_OVERLOAD(8TUPLE_SIZE_2,ORDER_PP_TUPLE_SIZE_MAX_11_OR_MORE P##t)(,P##t,P##n)
#define ORDER_PP_8TUPLE_SIZE_2_1(P,t,n) )(1)P##n
#define ORDER_PP_8TUPLE_SIZE_2_2(P,t,n) )(2)P##n
#define ORDER_PP_8TUPLE_SIZE_2_3(P,t,n) )(3)P##n
#define ORDER_PP_8TUPLE_SIZE_2_4(P,t,n) )(4)P##n
#define ORDER_PP_8TUPLE_SIZE_2_5(P,t,n) )(5)P##n
#define ORDER_PP_8TUPLE_SIZE_2_6(P,t,n) )(6)P##n
#define ORDER_PP_8TUPLE_SIZE_2_7(P,t,n) )(7)P##n
#define ORDER_PP_8TUPLE_SIZE_2_8(P,t,n) )(8)P##n
#define ORDER_PP_8TUPLE_SIZE_2_9(P,t,n) )(9)P##n
#define ORDER_PP_8TUPLE_SIZE_2_10(P,t,n) )(0)ORDER_PP_NAT_SUCC P##n
#define ORDER_PP_8TUPLE_SIZE_2_11_OR_MORE(P,t,n) (,(,ORDER_PP_TUPLE_DROP_10 P##t),8TUPLE_SIZE_2,ORDER_PP_NAT_SUCC P##n,)

#define ORDER_PP_DEF_8tuple_to_seq ORDER_PP_FN_CM(1,8TUPLE_TO_SEQ,0IS_TUPLE)
#define ORDER_PP_8TUPLE_TO_SEQ(P,t,...) (,ORDER_PP_FY(TUPLE_TO_SEQ,(,ORDER_PP_REM P##t)),P##__VA_ARGS__)

#define ORDER_PP_TUPLE_TO_SEQ(P,...) ORDER_PP_PM(,ORDER_PP_OVERLOAD(TUPLE_TO_SEQ,ORDER_PP_TUPLE_SIZE_MAX_11_OR_MORE(,P##__VA_ARGS__))(,P##__VA_ARGS__),8STOP,)
#define ORDER_PP_TUPLE_TO_SEQ_1(P,_0) (P##_0)
#define ORDER_PP_TUPLE_TO_SEQ_2(P,_0,_1) (P##_0)(P##_1)
#define ORDER_PP_TUPLE_TO_SEQ_3(P,_0,_1,_2) (P##_0)(P##_1)(P##_2)
#define ORDER_PP_TUPLE_TO_SEQ_4(P,_0,_1,_2,_3) (P##_0)(P##_1)(P##_2)(P##_3)
#define ORDER_PP_TUPLE_TO_SEQ_5(P,_0,_1,_2,_3,_4) (P##_0)(P##_1)(P##_2)(P##_3)(P##_4)
#define ORDER_PP_TUPLE_TO_SEQ_6(P,_0,_1,_2,_3,_4,_5) (P##_0)(P##_1)(P##_2)(P##_3)(P##_4)(P##_5)
#define ORDER_PP_TUPLE_TO_SEQ_7(P,_0,_1,_2,_3,_4,_5,_6) (P##_0)(P##_1)(P##_2)(P##_3)(P##_4)(P##_5)(P##_6)
#define ORDER_PP_TUPLE_TO_SEQ_8(P,_0,_1,_2,_3,_4,_5,_6,_7) (P##_0)(P##_1)(P##_2)(P##_3)(P##_4)(P##_5)(P##_6)(P##_7)
#define ORDER_PP_TUPLE_TO_SEQ_9(P,_0,_1,_2,_3,_4,_5,_6,_7,_8) (P##_0)(P##_1)(P##_2)(P##_3)(P##_4)(P##_5)(P##_6)(P##_7)(P##_8)
#define ORDER_PP_TUPLE_TO_SEQ_10(P,_0,_1,_2,_3,_4,_5,_6,_7,_8,_9) (P##_0)(P##_1)(P##_2)(P##_3)(P##_4)(P##_5)(P##_6)(P##_7)(P##_8)(P##_9)
#define ORDER_PP_TUPLE_TO_SEQ_11_OR_MORE(P,_0,_1,_2,_3,_4,_5,_6,_7,_8,_9,...) (P##_0)(P##_1)(P##_2)(P##_3)(P##_4)(P##_5)(P##_6)(P##_7)(P##_8)(P##_9)ORDER_PP_NIL,8TUPLE_TO_SEQ_2,(,P##__VA_ARGS__)
#define ORDER_PP_8TUPLE_TO_SEQ_2(P,s,t,...) (,s##P()ORDER_PP_OVERLOAD(TUPLE_TO_SEQ,ORDER_PP_TUPLE_SIZE_MAX_11_OR_MORE P##t)P##t,P##__VA_ARGS__)

// Only some higher-order functions for convenience

#define ORDER_PP_DEF_8tuple_map                                 \
ORDER_PP_FN(8fn(8F, 8T,                                         \
                8seq_to_tuple(8seq_map(8F,                      \
                                       8tuple_to_seq(8T)))))

// Details

#define ORDER_PP_0IS_TUPLE(P,x) ORDER_PP_TEST(ORDER_PP_,ORDER_PP_IS_EDIBLE_TEST x##P,0IS_TUPLE_B,0NEVER)(ORDER_PP_EAT x##P)
#define ORDER_PP_0IS_TUPLE_B(x) ORDER_PP_IS_NIL(,x)

#define ORDER_PP_IS_TUPLE_SIZE_1(P,...) ORDER_PP_IS_TUPLE_SIZE_1_B(P##__VA_ARGS__,ORDER_PP_COMMA_1,)
#define ORDER_PP_IS_TUPLE_SIZE_1_B(_,x,...) ORDER_PP_TUPLE_AT_1(ORDER_PP_IF_,x,0,)

#define ORDER_PP_IS_TUPLE_SIZE_2(P,...) ORDER_PP_IS_TUPLE_SIZE_2_B(P##__VA_ARGS__,ORDER_PP_COMMA_1,,)
#define ORDER_PP_IS_TUPLE_SIZE_2_B(_,A,x,...) ORDER_PP_TUPLE_AT_1(ORDER_PP_IF_,x,0,)

#define ORDER_PP_TUPLE_LAST(P,...) ORDER_PP_OVERLOAD(TUPLE_LAST,ORDER_PP_TUPLE_SIZE_MAX_11_OR_MORE(,P##__VA_ARGS__))(,P##__VA_ARGS__)
#define ORDER_PP_TUPLE_LAST_1(P,_0) P##_0
#define ORDER_PP_TUPLE_LAST_2(P,_0,_1) P##_1
#define ORDER_PP_TUPLE_LAST_3(P,_0,_1,_2) P##_2
#define ORDER_PP_TUPLE_LAST_4(P,_0,_1,_2,_3) P##_3
#define ORDER_PP_TUPLE_LAST_5(P,_0,_1,_2,_3,_4) P##_4
#define ORDER_PP_TUPLE_LAST_6(P,_0,_1,_2,_3,_4,_5) P##_5
#define ORDER_PP_TUPLE_LAST_7(P,_0,_1,_2,_3,_4,_5,_6) P##_6
#define ORDER_PP_TUPLE_LAST_8(P,_0,_1,_2,_3,_4,_5,_6,_7) P##_7
#define ORDER_PP_TUPLE_LAST_9(P,_0,_1,_2,_3,_4,_5,_6,_7,_8) P##_8
#define ORDER_PP_TUPLE_LAST_10(P,_0,_1,_2,_3,_4,_5,_6,_7,_8,_9) P##_9
#define ORDER_PP_TUPLE_LAST_11_OR_MORE() // This should never occure.

#define ORDER_PP_TUPLE_FIRST(P,...) ORDER_PP_TUPLE_AT_0(,P##__VA_ARGS__,)
#define ORDER_PP_TUPLE_REST(P,_0,...) P##__VA_ARGS__

#define ORDER_PP_8TUPLE_DROP_100N(P,n,t,...) ORDER_PP_NAT_IS_ZERO P##n(,ORDER_PP_8EXIT_TUPLE P##t,(,ORDER_PP_NAT_PRED P##n,8TUPLE_DROP_100N,(,ORDER_PP_TUPLE_DROP_100 t##P),))

#define ORDER_PP_TUPLE_SIZE_MAX_11_OR_MORE(P,...) ORDER_PP_TUPLE_SIZE_MAX_11_OR_MORE_B(P##__VA_ARGS__,ORDER_PP_COMMA_10,ORDER_PP_COMMA_9,ORDER_PP_COMMA_8,ORDER_PP_COMMA_7,ORDER_PP_COMMA_6,ORDER_PP_COMMA_5,ORDER_PP_COMMA_4,ORDER_PP_COMMA_3,ORDER_PP_COMMA_2,ORDER_PP_COMMA_1,)
#define ORDER_PP_TUPLE_SIZE_MAX_11_OR_MORE_B(_,A,B,C,D,E,F,G,H,I,x,...) ORDER_PP_TUPLE_AT_1(,x,11_OR_MORE,)

#define ORDER_PP_8EXIT_TUPLE(P,...) )P##__VA_ARGS__

#include "order/prelude/tuple_tables.h"
