// (C) Copyright Vesa Karvonen 2004.
//
// Distributed under the Boost Software License, Version 1.0.

#define ORDER_PP_TUPLE_AT_0(_,A,...) _##A
#define ORDER_PP_TUPLE_AT_1(_,A,B,...) _##B
#define ORDER_PP_TUPLE_AT_2(_,A,B,C,...) _##C
#define ORDER_PP_TUPLE_AT_3(_,A,B,C,D,...) _##D
#define ORDER_PP_TUPLE_AT_4(_,A,B,C,D,E,...) _##E
#define ORDER_PP_TUPLE_AT_5(_,A,B,C,D,E,F,...) _##F
#define ORDER_PP_TUPLE_AT_6(_,A,B,C,D,E,F,G,...) _##G
#define ORDER_PP_TUPLE_AT_7(_,A,B,C,D,E,F,G,H,...) _##H
#define ORDER_PP_TUPLE_AT_8(_,A,B,C,D,E,F,G,H,I,...) _##I
#define ORDER_PP_TUPLE_AT_9(_,A,B,C,D,E,F,G,H,I,J,...) _##J

#define ORDER_PP_TUPLE_REST_0(_,...) _##__VA_ARGS__
#define ORDER_PP_TUPLE_REST_1(_,A,...) _##__VA_ARGS__
#define ORDER_PP_TUPLE_REST_2(_,A,B,...) _##__VA_ARGS__
#define ORDER_PP_TUPLE_REST_3(_,A,B,C,...) _##__VA_ARGS__
#define ORDER_PP_TUPLE_REST_4(_,A,B,C,D,...) _##__VA_ARGS__
#define ORDER_PP_TUPLE_REST_5(_,A,B,C,D,E,...) _##__VA_ARGS__
#define ORDER_PP_TUPLE_REST_6(_,A,B,C,D,E,F,...) _##__VA_ARGS__
#define ORDER_PP_TUPLE_REST_7(_,A,B,C,D,E,F,G,...) _##__VA_ARGS__
#define ORDER_PP_TUPLE_REST_8(_,A,B,C,D,E,F,G,H,...) _##__VA_ARGS__
#define ORDER_PP_TUPLE_REST_9(_,A,B,C,D,E,F,G,H,I,...) _##__VA_ARGS__
#define ORDER_PP_TUPLE_REST_10(_,A,B,C,D,E,F,G,H,I,J,...) _##__VA_ARGS__
#define ORDER_PP_TUPLE_REST_11(_,A,B,C,D,E,F,G,H,I,J,K,...) _##__VA_ARGS__
#define ORDER_PP_TUPLE_REST_12(_,A,B,C,D,E,F,G,H,I,J,K,L,...) _##__VA_ARGS__
#define ORDER_PP_TUPLE_REST_13(_,A,B,C,D,E,F,G,H,I,J,K,L,M,...) _##__VA_ARGS__
#define ORDER_PP_TUPLE_REST_14(_,A,B,C,D,E,F,G,H,I,J,K,L,M,N,...) _##__VA_ARGS__
#define ORDER_PP_TUPLE_REST_15(_,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,...) _##__VA_ARGS__
#define ORDER_PP_TUPLE_REST_16(_,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,...) _##__VA_ARGS__
#define ORDER_PP_TUPLE_REST_17(_,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,...) _##__VA_ARGS__
#define ORDER_PP_TUPLE_REST_18(_,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,...) _##__VA_ARGS__
#define ORDER_PP_TUPLE_REST_19(_,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,...) _##__VA_ARGS__
#define ORDER_PP_TUPLE_REST_20(_,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,...) _##__VA_ARGS__
#define ORDER_PP_TUPLE_REST_21(_,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,...) _##__VA_ARGS__
#define ORDER_PP_TUPLE_REST_22(_,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,...) _##__VA_ARGS__
#define ORDER_PP_TUPLE_REST_23(_,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,...) _##__VA_ARGS__
#define ORDER_PP_TUPLE_REST_24(_,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,...) _##__VA_ARGS__
#define ORDER_PP_TUPLE_REST_25(_,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,...) _##__VA_ARGS__
#define ORDER_PP_TUPLE_REST_26(_,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z,...) _##__VA_ARGS__
#define ORDER_PP_TUPLE_REST_27(_,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z,a,...) _##__VA_ARGS__
#define ORDER_PP_TUPLE_REST_28(_,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z,a,b,...) _##__VA_ARGS__
#define ORDER_PP_TUPLE_REST_29(_,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z,a,b,c,...) _##__VA_ARGS__
#define ORDER_PP_TUPLE_REST_30(_,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z,a,b,c,d,...) _##__VA_ARGS__
#define ORDER_PP_TUPLE_REST_31(_,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z,a,b,c,d,e,...) _##__VA_ARGS__
#define ORDER_PP_TUPLE_REST_32(_,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z,a,b,c,d,e,f,...) _##__VA_ARGS__
#define ORDER_PP_TUPLE_REST_33(_,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z,a,b,c,d,e,f,g,...) _##__VA_ARGS__
#define ORDER_PP_TUPLE_REST_34(_,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z,a,b,c,d,e,f,g,h,...) _##__VA_ARGS__
#define ORDER_PP_TUPLE_REST_35(_,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z,a,b,c,d,e,f,g,h,i,...) _##__VA_ARGS__
#define ORDER_PP_TUPLE_REST_36(_,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z,a,b,c,d,e,f,g,h,i,j,...) _##__VA_ARGS__
#define ORDER_PP_TUPLE_REST_37(_,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z,a,b,c,d,e,f,g,h,i,j,k,...) _##__VA_ARGS__
#define ORDER_PP_TUPLE_REST_38(_,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z,a,b,c,d,e,f,g,h,i,j,k,l,...) _##__VA_ARGS__
#define ORDER_PP_TUPLE_REST_39(_,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z,a,b,c,d,e,f,g,h,i,j,k,l,m,...) _##__VA_ARGS__
#define ORDER_PP_TUPLE_REST_40(_,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z,a,b,c,d,e,f,g,h,i,j,k,l,m,n,...) _##__VA_ARGS__
#define ORDER_PP_TUPLE_REST_41(_,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,...) _##__VA_ARGS__
#define ORDER_PP_TUPLE_REST_42(_,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,...) _##__VA_ARGS__
#define ORDER_PP_TUPLE_REST_43(_,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,...) _##__VA_ARGS__
#define ORDER_PP_TUPLE_REST_44(_,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,...) _##__VA_ARGS__
#define ORDER_PP_TUPLE_REST_45(_,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,...) _##__VA_ARGS__
#define ORDER_PP_TUPLE_REST_46(_,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,...) _##__VA_ARGS__
#define ORDER_PP_TUPLE_REST_47(_,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,...) _##__VA_ARGS__
#define ORDER_PP_TUPLE_REST_48(_,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,...) _##__VA_ARGS__
#define ORDER_PP_TUPLE_REST_49(_,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,...) _##__VA_ARGS__
#define ORDER_PP_TUPLE_REST_50(_,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,...) _##__VA_ARGS__
#define ORDER_PP_TUPLE_REST_51(_,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,...) _##__VA_ARGS__
#define ORDER_PP_TUPLE_REST_52(_,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,...) _##__VA_ARGS__
#define ORDER_PP_TUPLE_REST_53(_,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A1,...) _##__VA_ARGS__
#define ORDER_PP_TUPLE_REST_54(_,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A1,B1,...) _##__VA_ARGS__
#define ORDER_PP_TUPLE_REST_55(_,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A1,B1,C1,...) _##__VA_ARGS__
#define ORDER_PP_TUPLE_REST_56(_,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A1,B1,C1,D1,...) _##__VA_ARGS__
#define ORDER_PP_TUPLE_REST_57(_,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A1,B1,C1,D1,E1,...) _##__VA_ARGS__
#define ORDER_PP_TUPLE_REST_58(_,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A1,B1,C1,D1,E1,F1,...) _##__VA_ARGS__
#define ORDER_PP_TUPLE_REST_59(_,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A1,B1,C1,D1,E1,F1,G1,...) _##__VA_ARGS__
#define ORDER_PP_TUPLE_REST_60(_,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A1,B1,C1,D1,E1,F1,G1,H1,...) _##__VA_ARGS__
#define ORDER_PP_TUPLE_REST_61(_,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A1,B1,C1,D1,E1,F1,G1,H1,I1,...) _##__VA_ARGS__
#define ORDER_PP_TUPLE_REST_62(_,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A1,B1,C1,D1,E1,F1,G1,H1,I1,J1,...) _##__VA_ARGS__
#define ORDER_PP_TUPLE_REST_63(_,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A1,B1,C1,D1,E1,F1,G1,H1,I1,J1,K1,...) _##__VA_ARGS__
#define ORDER_PP_TUPLE_REST_64(_,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A1,B1,C1,D1,E1,F1,G1,H1,I1,J1,K1,L1,...) _##__VA_ARGS__
#define ORDER_PP_TUPLE_REST_65(_,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A1,B1,C1,D1,E1,F1,G1,H1,I1,J1,K1,L1,M1,...) _##__VA_ARGS__
#define ORDER_PP_TUPLE_REST_66(_,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A1,B1,C1,D1,E1,F1,G1,H1,I1,J1,K1,L1,M1,N1,...) _##__VA_ARGS__
#define ORDER_PP_TUPLE_REST_67(_,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A1,B1,C1,D1,E1,F1,G1,H1,I1,J1,K1,L1,M1,N1,O1,...) _##__VA_ARGS__
#define ORDER_PP_TUPLE_REST_68(_,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A1,B1,C1,D1,E1,F1,G1,H1,I1,J1,K1,L1,M1,N1,O1,P1,...) _##__VA_ARGS__
#define ORDER_PP_TUPLE_REST_69(_,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A1,B1,C1,D1,E1,F1,G1,H1,I1,J1,K1,L1,M1,N1,O1,P1,Q1,...) _##__VA_ARGS__
#define ORDER_PP_TUPLE_REST_70(_,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A1,B1,C1,D1,E1,F1,G1,H1,I1,J1,K1,L1,M1,N1,O1,P1,Q1,R1,...) _##__VA_ARGS__
#define ORDER_PP_TUPLE_REST_71(_,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A1,B1,C1,D1,E1,F1,G1,H1,I1,J1,K1,L1,M1,N1,O1,P1,Q1,R1,S1,...) _##__VA_ARGS__
#define ORDER_PP_TUPLE_REST_72(_,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A1,B1,C1,D1,E1,F1,G1,H1,I1,J1,K1,L1,M1,N1,O1,P1,Q1,R1,S1,T1,...) _##__VA_ARGS__
#define ORDER_PP_TUPLE_REST_73(_,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A1,B1,C1,D1,E1,F1,G1,H1,I1,J1,K1,L1,M1,N1,O1,P1,Q1,R1,S1,T1,U1,...) _##__VA_ARGS__
#define ORDER_PP_TUPLE_REST_74(_,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A1,B1,C1,D1,E1,F1,G1,H1,I1,J1,K1,L1,M1,N1,O1,P1,Q1,R1,S1,T1,U1,V1,...) _##__VA_ARGS__
#define ORDER_PP_TUPLE_REST_75(_,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A1,B1,C1,D1,E1,F1,G1,H1,I1,J1,K1,L1,M1,N1,O1,P1,Q1,R1,S1,T1,U1,V1,W1,...) _##__VA_ARGS__
#define ORDER_PP_TUPLE_REST_76(_,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A1,B1,C1,D1,E1,F1,G1,H1,I1,J1,K1,L1,M1,N1,O1,P1,Q1,R1,S1,T1,U1,V1,W1,X1,...) _##__VA_ARGS__
#define ORDER_PP_TUPLE_REST_77(_,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A1,B1,C1,D1,E1,F1,G1,H1,I1,J1,K1,L1,M1,N1,O1,P1,Q1,R1,S1,T1,U1,V1,W1,X1,Y1,...) _##__VA_ARGS__
#define ORDER_PP_TUPLE_REST_78(_,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A1,B1,C1,D1,E1,F1,G1,H1,I1,J1,K1,L1,M1,N1,O1,P1,Q1,R1,S1,T1,U1,V1,W1,X1,Y1,Z1,...) _##__VA_ARGS__
#define ORDER_PP_TUPLE_REST_79(_,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A1,B1,C1,D1,E1,F1,G1,H1,I1,J1,K1,L1,M1,N1,O1,P1,Q1,R1,S1,T1,U1,V1,W1,X1,Y1,Z1,a1,...) _##__VA_ARGS__
#define ORDER_PP_TUPLE_REST_80(_,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A1,B1,C1,D1,E1,F1,G1,H1,I1,J1,K1,L1,M1,N1,O1,P1,Q1,R1,S1,T1,U1,V1,W1,X1,Y1,Z1,a1,b1,...) _##__VA_ARGS__
#define ORDER_PP_TUPLE_REST_81(_,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A1,B1,C1,D1,E1,F1,G1,H1,I1,J1,K1,L1,M1,N1,O1,P1,Q1,R1,S1,T1,U1,V1,W1,X1,Y1,Z1,a1,b1,c1,...) _##__VA_ARGS__
#define ORDER_PP_TUPLE_REST_82(_,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A1,B1,C1,D1,E1,F1,G1,H1,I1,J1,K1,L1,M1,N1,O1,P1,Q1,R1,S1,T1,U1,V1,W1,X1,Y1,Z1,a1,b1,c1,d1,...) _##__VA_ARGS__
#define ORDER_PP_TUPLE_REST_83(_,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A1,B1,C1,D1,E1,F1,G1,H1,I1,J1,K1,L1,M1,N1,O1,P1,Q1,R1,S1,T1,U1,V1,W1,X1,Y1,Z1,a1,b1,c1,d1,e1,...) _##__VA_ARGS__
#define ORDER_PP_TUPLE_REST_84(_,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A1,B1,C1,D1,E1,F1,G1,H1,I1,J1,K1,L1,M1,N1,O1,P1,Q1,R1,S1,T1,U1,V1,W1,X1,Y1,Z1,a1,b1,c1,d1,e1,f1,...) _##__VA_ARGS__
#define ORDER_PP_TUPLE_REST_85(_,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A1,B1,C1,D1,E1,F1,G1,H1,I1,J1,K1,L1,M1,N1,O1,P1,Q1,R1,S1,T1,U1,V1,W1,X1,Y1,Z1,a1,b1,c1,d1,e1,f1,g1,...) _##__VA_ARGS__
#define ORDER_PP_TUPLE_REST_86(_,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A1,B1,C1,D1,E1,F1,G1,H1,I1,J1,K1,L1,M1,N1,O1,P1,Q1,R1,S1,T1,U1,V1,W1,X1,Y1,Z1,a1,b1,c1,d1,e1,f1,g1,h1,...) _##__VA_ARGS__
#define ORDER_PP_TUPLE_REST_87(_,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A1,B1,C1,D1,E1,F1,G1,H1,I1,J1,K1,L1,M1,N1,O1,P1,Q1,R1,S1,T1,U1,V1,W1,X1,Y1,Z1,a1,b1,c1,d1,e1,f1,g1,h1,i1,...) _##__VA_ARGS__
#define ORDER_PP_TUPLE_REST_88(_,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A1,B1,C1,D1,E1,F1,G1,H1,I1,J1,K1,L1,M1,N1,O1,P1,Q1,R1,S1,T1,U1,V1,W1,X1,Y1,Z1,a1,b1,c1,d1,e1,f1,g1,h1,i1,j1,...) _##__VA_ARGS__
#define ORDER_PP_TUPLE_REST_89(_,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A1,B1,C1,D1,E1,F1,G1,H1,I1,J1,K1,L1,M1,N1,O1,P1,Q1,R1,S1,T1,U1,V1,W1,X1,Y1,Z1,a1,b1,c1,d1,e1,f1,g1,h1,i1,j1,k1,...) _##__VA_ARGS__
#define ORDER_PP_TUPLE_REST_90(_,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A1,B1,C1,D1,E1,F1,G1,H1,I1,J1,K1,L1,M1,N1,O1,P1,Q1,R1,S1,T1,U1,V1,W1,X1,Y1,Z1,a1,b1,c1,d1,e1,f1,g1,h1,i1,j1,k1,l1,...) _##__VA_ARGS__
#define ORDER_PP_TUPLE_REST_91(_,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A1,B1,C1,D1,E1,F1,G1,H1,I1,J1,K1,L1,M1,N1,O1,P1,Q1,R1,S1,T1,U1,V1,W1,X1,Y1,Z1,a1,b1,c1,d1,e1,f1,g1,h1,i1,j1,k1,l1,m1,...) _##__VA_ARGS__
#define ORDER_PP_TUPLE_REST_92(_,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A1,B1,C1,D1,E1,F1,G1,H1,I1,J1,K1,L1,M1,N1,O1,P1,Q1,R1,S1,T1,U1,V1,W1,X1,Y1,Z1,a1,b1,c1,d1,e1,f1,g1,h1,i1,j1,k1,l1,m1,n1,...) _##__VA_ARGS__
#define ORDER_PP_TUPLE_REST_93(_,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A1,B1,C1,D1,E1,F1,G1,H1,I1,J1,K1,L1,M1,N1,O1,P1,Q1,R1,S1,T1,U1,V1,W1,X1,Y1,Z1,a1,b1,c1,d1,e1,f1,g1,h1,i1,j1,k1,l1,m1,n1,o1,...) _##__VA_ARGS__
#define ORDER_PP_TUPLE_REST_94(_,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A1,B1,C1,D1,E1,F1,G1,H1,I1,J1,K1,L1,M1,N1,O1,P1,Q1,R1,S1,T1,U1,V1,W1,X1,Y1,Z1,a1,b1,c1,d1,e1,f1,g1,h1,i1,j1,k1,l1,m1,n1,o1,p1,...) _##__VA_ARGS__
#define ORDER_PP_TUPLE_REST_95(_,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A1,B1,C1,D1,E1,F1,G1,H1,I1,J1,K1,L1,M1,N1,O1,P1,Q1,R1,S1,T1,U1,V1,W1,X1,Y1,Z1,a1,b1,c1,d1,e1,f1,g1,h1,i1,j1,k1,l1,m1,n1,o1,p1,q1,...) _##__VA_ARGS__
#define ORDER_PP_TUPLE_REST_96(_,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A1,B1,C1,D1,E1,F1,G1,H1,I1,J1,K1,L1,M1,N1,O1,P1,Q1,R1,S1,T1,U1,V1,W1,X1,Y1,Z1,a1,b1,c1,d1,e1,f1,g1,h1,i1,j1,k1,l1,m1,n1,o1,p1,q1,r1,...) _##__VA_ARGS__
#define ORDER_PP_TUPLE_REST_97(_,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A1,B1,C1,D1,E1,F1,G1,H1,I1,J1,K1,L1,M1,N1,O1,P1,Q1,R1,S1,T1,U1,V1,W1,X1,Y1,Z1,a1,b1,c1,d1,e1,f1,g1,h1,i1,j1,k1,l1,m1,n1,o1,p1,q1,r1,s1,...) _##__VA_ARGS__
#define ORDER_PP_TUPLE_REST_98(_,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A1,B1,C1,D1,E1,F1,G1,H1,I1,J1,K1,L1,M1,N1,O1,P1,Q1,R1,S1,T1,U1,V1,W1,X1,Y1,Z1,a1,b1,c1,d1,e1,f1,g1,h1,i1,j1,k1,l1,m1,n1,o1,p1,q1,r1,s1,t1,...) _##__VA_ARGS__
#define ORDER_PP_TUPLE_REST_99(_,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A1,B1,C1,D1,E1,F1,G1,H1,I1,J1,K1,L1,M1,N1,O1,P1,Q1,R1,S1,T1,U1,V1,W1,X1,Y1,Z1,a1,b1,c1,d1,e1,f1,g1,h1,i1,j1,k1,l1,m1,n1,o1,p1,q1,r1,s1,t1,u1,...) _##__VA_ARGS__
#define ORDER_PP_TUPLE_REST_100(_,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A1,B1,C1,D1,E1,F1,G1,H1,I1,J1,K1,L1,M1,N1,O1,P1,Q1,R1,S1,T1,U1,V1,W1,X1,Y1,Z1,a1,b1,c1,d1,e1,f1,g1,h1,i1,j1,k1,l1,m1,n1,o1,p1,q1,r1,s1,t1,u1,v1,...) _##__VA_ARGS__
