#ifndef ORDER_INC_ORDER_LIB_PARAMS_H_VAJK20040620
#define ORDER_INC_ORDER_LIB_PARAMS_H_VAJK20040620

// (C) Copyright Vesa Karvonen 2004.
//
// Distributed under the Boost Software License, Version 1.0.
// (See accompanying file LICENSE.)

#define ORDER_PP_DEF_8emit_params ORDER_PP_FN_CM(3,8EMIT_PARAMS,0IS_NUM,0IS_NUM,0IS_ANY)
#define ORDER_PP_8EMIT_PARAMS(P,p,i1,i0,...) (,,P##__VA_ARGS__)ORDER_PP_NUM_EQUAL(,P##i0,P##i1)(,,(,2,ORDER_PP_ENUM_PARAMS_WITH_A_DEFAULT,(,P##i0,P##i1,P##p,)))

#define ORDER_PP_DEF_8emit_trailing_params ORDER_PP_FN_CM(3,8EMIT_TRAILING_PARAMS,0IS_NUM,0IS_NUM,0IS_ANY)
#define ORDER_PP_8EMIT_TRAILING_PARAMS(P,p,i1,i0,...) (,,P##__VA_ARGS__)(,2,ORDER_PP_ENUM_TRAILING_PARAMS_WITH_A_DEFAULT,(,P##i0,P##i1,P##p,))

#define ORDER_PP_DEF_8emit_params_with_a_default ORDER_PP_FN_CM(4,8EMIT_PARAMS_WITH_A_DEFAULT,0IS_NUM,0IS_NUM,0IS_ANY,0IS_ANY)
#define ORDER_PP_8EMIT_PARAMS_WITH_A_DEFAULT(P,d,p,i1,i0,...) (,,P##__VA_ARGS__)ORDER_PP_NUM_EQUAL(,P##i0,P##i1)(,,(,2,ORDER_PP_ENUM_PARAMS_WITH_A_DEFAULT,(,P##i0,P##i1,P##p,P##d)))
#define ORDER_PP_ENUM_PARAMS_WITH_A_DEFAULT(P,i0,i1,p,d) ORDER_PP_FX(OPEN,(ORDER_PP_ENUM_TRAILING_PARAMS_WITH_A_DEFAULT(,P##i0,P##i1,P##p,P##d)))

#define ORDER_PP_DEF_8emit_trailing_params_with_a_default ORDER_PP_FN_CM(4,8EMIT_TRAILING_PARAMS_WITH_A_DEFAULT,0IS_NUM,0IS_NUM,0IS_ANY,0IS_ANY)
#define ORDER_PP_8EMIT_TRAILING_PARAMS_WITH_A_DEFAULT(P,d,p,i1,i0,...) (,,P##__VA_ARGS__)(,2,ORDER_PP_ENUM_TRAILING_PARAMS_WITH_A_DEFAULT,(,P##i0,P##i1,P##p,P##d))
#define ORDER_PP_ENUM_TRAILING_PARAMS_WITH_A_DEFAULT(P,i0,i1,p,d) ORDER_PP_CM(,P##i0,8FOR_EACH_IN_RANGE,P##i1,(,8EMIT_TRAILING_PARAM_WITH_A_DEFAULT,P##p,d##P),8STOP,)
#define ORDER_PP_8EMIT_TRAILING_PARAM_WITH_A_DEFAULT(P,i,p,d,K,...) ORDER_PP_##K(,,P##__VA_ARGS__),ORDER_PP_CAT(P##p,ORDER_PP_NUM_TO_LIT(,P##i))P##d

#endif
