#!/bin/bash

# (C) Copyright Vesa Karvonen 2004.
#
#    Distributed under the Boost Software License, Version 1.0.

gcc -std=c99 \
    -Wall -Werror \
    -pedantic-errors \
    -Os \
    -I ../../inc/ \
    -I ../../../chaos-pp/ \
    -lgc \
    -o lambda \
    *.c && \
strip lambda
