#!/bin/bash

# (C) Copyright Vesa Karvonen 2004.
#
# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file LICENSE.)

if cpp -I ../../inc/ \
       -I ../../../chaos-pp/ \
       checked_malloc.c &> /dev/null ; then
    gc_option='-lgc'
else
    echo "Warning: Not using GC."
    gc_option='-DCHECKED_MALLOC_NO_GC=1'
fi

gcc -std=c99 \
    -Wall -Werror \
    -pedantic-errors \
    -Os \
    -I ../../inc/ \
    -I ../../../chaos-pp/ \
    $gc_option \
    -o lambda \
    *.c && \
strip lambda
